/**
 * Copyright (c) 2015-2019 Shanghai Fullhan Microelectronics Co., Ltd.
 *
 * SPDX-License-Identifier: Apache-2.0
 *
 *
 * Change Logs:
 * Date           Author       Notes
 *
 */

#ifndef __CLOCK_CONFIG_H__
#define __CLOCK_CONFIG_H__

#include <rtdef.h>
#include "fh_clock.h"
#include "fh_pmu.h"

#define OSC_FREQUENCY  24000000   /*24M hz*/

#define RT_UINT9_MAX                    0x1ff
#define RT_UINT8_MAX                    0xff
#define RT_UINT7_MAX                    0x7f
#define RT_UINT6_MAX                    0x3f
#define RT_UINT5_MAX                    0x1f
#define RT_UINT4_MAX                    0xf
#define RT_UINT3_MAX                    0x7
#define RT_UINT2_MAX                    0x3
#define RT_UINT1_MAX                    0x1

struct clk fh_clk_list_low[] = {
    {
        .name                  = "osc_clk",
        .clk_out_rate          = OSC_FREQUENCY,
        .flag                  = CLOCK_FIXED,
    },
    {
        .name                  = "ddr_clk",
        .flag                  = CLOCK_DDR,
        .clk_config            = UNCONFIG,
        .clk_div.reg_offset    = CEN_GLB_APB_REG_BASE + 0x438,
        .clk_div.mask          = 0xf000007,
        .clk_div1.reg_offset   = CEN_GLB_APB_REG_BASE + 0x43c,
        .clk_div1.mask         = 0x7ff,
    },
    {
        .name                  = "pll_clk",
        .flag                  = CLOCK_PLL2 | DIV,
        .clk_config            = UNCONFIG,
        .clk_div.reg_offset    = CEN_GLB_APB_REG_BASE + 0x41c,
        .clk_div.mask          = 0x7,
        .clk_div1.reg_offset   = CEN_GLB_APB_REG_BASE + 0x420,
        .clk_div1.mask         = 0x7ff,
    },
    {
        .name                  = "pll_div2",
        .flag                  = PREDIV,
        .clk_config            = UNCONFIG,
        .mult_parent           = {"pll_clk"},
        .pre_div               = 2,

    },
    {
        .name                  = "pll_div3",
        .flag                  = PREDIV,
        .clk_config            = UNCONFIG,
        .mult_parent           = {"pll_clk"},
        .pre_div               = 3,
    },
    {
        .name                  = "pll_div7",
        .flag                  = PREDIV,
        .clk_config            = UNCONFIG,
        .mult_parent           = {"pll_clk"},
        .pre_div               = 7,
    },
    {
        .name                  = "pll_div5",
        .flag                  = PREDIV,
        .clk_config            = UNCONFIG,
        .mult_parent           = {"pll_clk"},
        .pre_div               = 5,
    },
    {
        .name                  = "pll_div72",
        .flag                  = PREDIV,
        .clk_config            = UNCONFIG,
        .mult_parent           = {"pll_clk"},
        .pre_div               = 72,
    },
    {
        .name                  = "pll_900m",
        .clk_out_rate          = 900000000,
        .flag                  = CLOCK_FIXED,
    },
    {
        .name                  = "pll_600m",
        .clk_out_rate          = 600000000,
        .flag                  = CLOCK_FIXED,
    },
    {
        .name                  = "pll_514m",
        .clk_out_rate          = 514000000,
        .flag                  = CLOCK_FIXED,
    },
    {
        .name                  = "pll_360m",
        .clk_out_rate          = 360000000,
        .flag                  = CLOCK_FIXED,
    },
    {
        .name                  = "pll_257m",
        .clk_out_rate          = 257000000,
        .flag                  = CLOCK_FIXED,
    },
    {
        .name                  = "rtc",
        .clk_out_rate          = 32768,
        .flag                  = CLOCK_FIXED,
    },
    {
        .name                  = "rtc_gate",
        .flag                  = GATE,
        .clk_config            = UNCONFIG,
        .mult_parent           = {"rtc"},
        .clk_gate.reg_offset   = VEU_SYS_APB_REG_BASE + 0x14,
        .clk_gate.mask         = 0x800,
    },
    /*top*/
    {
        .name                  = "pll_200m_top",
        .flag                  = PREDIV,
        .clk_config            = UNCONFIG,
        .mult_parent           = {"pll_600m"},
        .pre_div               = 3,
    },
    {
        .name                  = "pll_100m_top",
        .flag                  = PREDIV,
        .clk_config            = UNCONFIG,
        .mult_parent           = {"pll_600m"},
        .pre_div               = 6,
    },
    {
        .name                  = "pll_128_5m_top",
        .flag                  = PREDIV,
        .clk_config            = UNCONFIG,
        .mult_parent           = {"pll_257m"},
        .pre_div               = 2,
    },
    {
        .name                  = "pll_75m_top",
        .flag                  = PREDIV,
        .clk_config            = UNCONFIG,
        .mult_parent           = {"pll_div3"},
        .pre_div               = 8,
    },
    {
        .name                  = "pll_64_25m_top",
        .flag                  = PREDIV,
        .clk_config            = UNCONFIG,
        .mult_parent           = {"pll_div7"},
        .pre_div               = 4,
    },
    {
        .name                  = "pll_50m_top",
        .flag                  = PREDIV,
        .clk_config            = UNCONFIG,
        .mult_parent           = {"pll_div3"},
        .pre_div               = 12,
    },
    {
        .name                  = "pll_33_3m_top",
        .flag                  = PREDIV,
        .clk_config            = UNCONFIG,
        .mult_parent           = {"pll_div3"},
        .pre_div               = 18,
    },
    {
        .name                  = "pll_25m_top",
        .flag                  = PREDIV,
        .clk_config            = UNCONFIG,
        .mult_parent           = {"pll_div72"},
        .pre_div               = 1,
    },
    {
        .name                  = "xtl_24m_top",
        .flag                  = PREDIV,
        .clk_config            = UNCONFIG,
        .mult_parent           = {"osc_clk"},
        .pre_div               = 1,
    },
    /*cpu*/
    {
        .name                  = "pll_600m_cpu",
        .flag                  = PREDIV,
        .clk_config            = UNCONFIG,
        .mult_parent           = {"pll_600m"},
        .pre_div               = 1,
    },
    {
        .name                  = "pll_450m_cpu",
        .flag                  = PREDIV,
        .clk_config            = UNCONFIG,
        .mult_parent           = {"pll_900m"},
        .pre_div               = 2,
    },
    {
        .name                  = "pll_225m_cpu2",
        .flag                  = PREDIV,
        .clk_config            = UNCONFIG,
        .mult_parent           = {"pll_450m_cpu"},
        .pre_div               = 2,
    },
    {
        .name                  = "pll_450_1m_cpu",
        .flag                  = PREDIV,
        .clk_config            = UNCONFIG,
        .mult_parent           = {"pll_div2"},
        .pre_div               = 2,
    },
    {
        .name                  = "pll_300m_cpu",
        .flag                  = PREDIV,
        .clk_config            = UNCONFIG,
        .mult_parent           = {"pll_600m"},
        .pre_div               = 2,
    },
	{
        .name                  = "pll_150m_cpu2",
        .flag                  = PREDIV,
        .clk_config            = UNCONFIG,
        .mult_parent           = {"pll_300m_cpu"},
        .pre_div               = 2,
    },
    {
        .name                  = "pll_300_1m_cpu",
        .flag                  = PREDIV,
        .clk_config            = UNCONFIG,
        .mult_parent           = {"pll_div3"},
        .pre_div               = 2,
    },
    {
        .name                  = "pll_257m_cpu",
        .flag                  = PREDIV,
        .clk_config            = UNCONFIG,
        .mult_parent           = {"pll_257m"},
        .pre_div               = 1,
    },
	{
        .name                  = "pll_128_5m_cpu2",
        .flag                  = PREDIV,
        .clk_config            = UNCONFIG,
        .mult_parent           = {"pll_257m_cpu"},
        .pre_div               = 2,
    },
    {
        .name                  = "pll_257_1m_cpu",
        .flag                  = PREDIV,
        .clk_config            = UNCONFIG,
        .mult_parent           = {"pll_div7"},
        .pre_div               = 1,
    },
    {
        .name                  = "pll_200m_cpu",
        .flag                  = PREDIV,
        .clk_config            = UNCONFIG,
        .mult_parent           = {"pll_600m"},
        .pre_div               = 3,
    },
    {
        .name                  = "pll_200_1m_cpu",
        .flag                  = PREDIV,
        .clk_config            = UNCONFIG,
        .mult_parent           = {"pll_div3"},
        .pre_div               = 3,
    },
    {
        .name                  = "pll_225m_cpu",
        .flag                  = PREDIV,
        .clk_config            = UNCONFIG,
        .mult_parent           = {"pll_900m"},
        .pre_div               = 4,
    },
    {
        .name                  = "pll_180_1m_cpu",
        .flag                  = PREDIV,
        .clk_config            = UNCONFIG,
        .mult_parent           = {"pll_div5"},
        .pre_div               = 2,
    },
    {
        .name                  = "pll_150m_cpu",
        .flag                  = PREDIV,
        .clk_config            = UNCONFIG,
        .mult_parent           = {"pll_600m"},
        .pre_div               = 4,
    },
    {
        .name                  = "pll_128_5m_cpu",
        .flag                  = PREDIV,
        .clk_config            = UNCONFIG,
        .mult_parent           = {"pll_257m"},
        .pre_div               = 2,
    },
    {
        .name                  = "pll_100m_cpu",
        .flag                  = PREDIV,
        .clk_config            = UNCONFIG,
        .mult_parent           = {"pll_div3"},
        .pre_div               = 6,
    },
    {
        .name                  = "pll_50m_cpu",
        .flag                  = PREDIV,
        .clk_config            = UNCONFIG,
        .mult_parent           = {"pll_div3"},
        .pre_div               = 12,
    },
    {
        .name                  = "pll_25m_cpu",
        .flag                  = PREDIV,
        .clk_config            = UNCONFIG,
        .mult_parent           = {"pll_div72"},
        .pre_div               = 1,
    },
    {
        .name                  = "xtl_24m_cpu",
        .flag                  = PREDIV,
        .clk_config            = UNCONFIG,
        .mult_parent           = {"osc_clk"},
        .pre_div               = 1,
    },
    {
        .name                  = "pll_20m_cpu",
        .flag                  = PREDIV,
        .clk_config            = UNCONFIG,
        .mult_parent           = {"pll_div5"},
        .pre_div               = 18,
    },
    {
        .name                  = "xtl_1m_cpu",
        .flag                  = PREDIV,
        .clk_config            = UNCONFIG,
        .mult_parent           = {"osc_clk"},
        .pre_div               = 24,
    },
    /*isp*/
    {
        .name                  = "pll_360m_isp",
        .flag                  = PREDIV,
        .clk_config            = UNCONFIG,
        .mult_parent           = {"pll_360m"},
        .pre_div               = 1,
    },
    {
        .name                  = "pll_180m_isp2",
        .flag                  = PREDIV,
        .clk_config            = UNCONFIG,
        .mult_parent           = {"pll_360m_isp"},
        .pre_div               = 2,
    },
    {
        .name                  = "pll_257m_isp",
        .flag                  = PREDIV,
        .clk_config            = UNCONFIG,
        .mult_parent           = {"pll_257m"},
        .pre_div               = 1,
    },
    {
        .name                  = "pll_128_5m_isp",
        .flag                  = PREDIV,
        .clk_config            = UNCONFIG,
        .mult_parent           = {"pll_257m_isp"},
        .pre_div               = 2,
    },
    {
        .name                  = "pll_200m_isp",
        .flag                  = PREDIV,
        .clk_config            = UNCONFIG,
        .mult_parent           = {"pll_600m"},
        .pre_div               = 3,
    },
    {
        .name                  = "pll_100m_isp2",
        .flag                  = PREDIV,
        .clk_config            = UNCONFIG,
        .mult_parent           = {"pll_200m_isp"},
        .pre_div               = 2,
    },
    {
        .name                  = "pll_180m_isp",
        .flag                  = PREDIV,
        .clk_config            = UNCONFIG,
        .mult_parent           = {"pll_360m"},
        .pre_div               = 2,
    },
    {
        .name                  = "pll_100m_isp",
        .flag                  = PREDIV,
        .clk_config            = UNCONFIG,
        .mult_parent           = {"pll_div3"},
        .pre_div               = 6,
    },
    {
        .name                  = "pll_50m_isp",
        .flag                  = PREDIV,
        .clk_config            = UNCONFIG,
        .mult_parent           = {"pll_div3"},
        .pre_div               = 12,
    },
    {
        .name                  = "xtl_24m_isp",
        .flag                  = PREDIV,
        .clk_config            = UNCONFIG,
        .mult_parent           = {"osc_clk"},
        .pre_div               = 1,
    },
    /*veu*/
    {
        .name                  = "xtl_24m_veu",
        .flag                  = PREDIV,
        .clk_config            = UNCONFIG,
        .mult_parent           = {"osc_clk"},
        .pre_div               = 1,
    },
    {
        .name                  = "pll_600m_veu",
        .flag                  = PREDIV,
        .clk_config            = UNCONFIG,
        .mult_parent           = {"pll_600m"},
        .pre_div               = 1,
    },
    {
        .name                  = "pll_300m_veu",
        .flag                  = PREDIV,
        .clk_config            = UNCONFIG,
        .mult_parent           = {"pll_600m_veu"},
        .pre_div               = 2,
    },
    {
        .name                  = "pll_514m_veu",
        .flag                  = PREDIV,
        .clk_config            = UNCONFIG,
        .mult_parent           = {"pll_514m"},
        .pre_div               = 1,
    },
    {
        .name                  = "pll_450m_veu",
        .flag                  = PREDIV,
        .clk_config            = UNCONFIG,
        .mult_parent           = {"pll_900m"},
        .pre_div               = 2,
    },
    {
        .name                  = "pll_225m_veu",
        .flag                  = PREDIV,
        .clk_config            = UNCONFIG,
        .mult_parent           = {"pll_450m_veu"},
        .pre_div               = 2,
    },
    {
        .name                  = "pll_360m_veu",
        .flag                  = PREDIV,
        .clk_config            = UNCONFIG,
        .mult_parent           = {"pll_360m"},
        .pre_div               = 1,
    },
	{
        .name                  = "pll_180m_veu",
        .flag                  = PREDIV,
        .clk_config            = UNCONFIG,
        .mult_parent           = {"pll_360m_veu"},
        .pre_div               = 2,
    },
    {
        .name                  = "pll_128_5m_veu",
        .flag                  = PREDIV,
        .clk_config            = UNCONFIG,
        .mult_parent           = {"pll_257m"},
        .pre_div               = 2,
    },
	{
        .name                  = "pll_64_25m_veu2",
        .flag                  = PREDIV,
        .clk_config            = UNCONFIG,
        .mult_parent           = {"pll_128_5m_veu"},
        .pre_div               = 2,
    },
    {
        .name                  = "pll_100m_veu",
        .flag                  = PREDIV,
        .clk_config            = UNCONFIG,
        .mult_parent           = {"pll_div3"},
        .pre_div               = 6,
    },
    {
        .name                  = "pll_64_25m_veu",
        .flag                  = PREDIV,
        .clk_config            = UNCONFIG,
        .mult_parent           = {"pll_div7"},
        .pre_div               = 4,
    },
    {
        .name                  = "pll_50m_veu",
        .flag                  = PREDIV,
        .clk_config            = UNCONFIG,
        .mult_parent           = {"pll_div3"},
        .pre_div               = 12,
    },
    /*dmc*/
    {
        .name                  = "xtl_24m_dmc",
        .flag                  = PREDIV,
        .clk_config            = UNCONFIG,
        .mult_parent           = {"osc_clk"},
        .pre_div               = 1,
    },
    {
        .name                  = "pll_50m_dmc",
        .flag                  = PREDIV,
        .clk_config            = UNCONFIG,
        .mult_parent           = {"pll_div3"},
        .pre_div               = 12,
    },
    {
        .name                  = "ddrpll_dmc",
        .clk_out_rate          = 800000000,
        .flag                  = CLOCK_FIXED,
    },
    {
        .name                  = "glb_apb",
        .flag                  = MUX | DIV,
        .clk_config            = UNCONFIG,
        .mult_parent           = {"xtl_24m_top", "pll_75m_top",
                        "pll_64_25m_top", "pll_100m_top"},
        .clk_mux.reg_offset    = TOP_CLK_RF_REG_BASE + 0x20,
        .clk_mux.mask          = 0x3,
        .clk_div.reg_offset    = TOP_CLK_RF_REG_BASE + 0x20,
        .clk_div.mask          = 0x700,
    },
    {
        .name                  = "pts_clk",
        .flag                  = MUX | DIV | GATE,
        .clk_config            = UNCONFIG,
        .mult_parent           = {"xtl_24m_top", "pll_25m_top", "pll_50m_top"},
        .clk_mux.reg_offset    = TOP_CLK_RF_REG_BASE + 0x24,
        .clk_mux.mask          = 0x3,
        .clk_div.reg_offset    = TOP_CLK_RF_REG_BASE + 0x24,
        .clk_div.mask          = 0x3f00,
        .clk_gate.reg_offset   = CEN_GLB_APB_REG_BASE + 0x400,
        .clk_gate.mask         = 0x1,
    },
    {
        .name                  = "sensor0_clk",
        .flag                  = MUX | DIV | GATE,
        .clk_config            = UNCONFIG,
        .mult_parent           = {"xtl_24m_top", "pll_33_3m_top",
                        "pll_64_25m_top", "pll_75m_top"},
        .clk_mux.reg_offset    = TOP_CLK_RF_REG_BASE + 0x28,
        .clk_mux.mask          = 0x3,
        .clk_div.reg_offset    = TOP_CLK_RF_REG_BASE + 0x28,
        .clk_div.mask          = 0xf00,
        .clk_gate.reg_offset   = CEN_GLB_APB_REG_BASE + 0x400,
        .clk_gate.mask         = 0x2,
    },
    {
        .name                  = "sensor1_clk",
        .flag                  = MUX | DIV | GATE,
        .clk_config            = UNCONFIG,
        .mult_parent           = {"xtl_24m_top", "pll_33_3m_top",
                        "pll_64_25m_top", "pll_75m_top"},
        .clk_mux.reg_offset    = TOP_CLK_RF_REG_BASE + 0x2c,
        .clk_mux.mask          = 0x3,
        .clk_div.reg_offset    = TOP_CLK_RF_REG_BASE + 0x2c,
        .clk_div.mask          = 0xf00,
        .clk_gate.reg_offset   = CEN_GLB_APB_REG_BASE + 0x400,
        .clk_gate.mask         = 0x4,
    },
    {
        .name                  = "pmu_clk",
        .flag                  = MUX | DIV | GATE,
        .clk_config            = UNCONFIG,
        .mult_parent           = {"rtc", "xtl_24m_top", "pll_75m_top"},
        .clk_mux.reg_offset    = TOP_CLK_RF_REG_BASE + 0x38,
        .clk_mux.mask          = 0x3,
        .clk_div.reg_offset    = TOP_CLK_RF_REG_BASE + 0x38,
        .clk_div.mask          = 0xf00,
        .clk_gate.reg_offset   = CEN_GLB_APB_REG_BASE + 0x200,
        .clk_gate.mask         = 0x100,
    },
    {
        .name                  = "deb_clk",
        .flag                  = MUX | DIV | GATE,
        .clk_config            = UNCONFIG,
        .mult_parent           = {"rtc", "xtl_24m_top", "pll_33_3m_top",
                        "pll_75m_top"},
        .clk_mux.reg_offset    = TOP_CLK_RF_REG_BASE + 0x3c,
        .clk_mux.mask          = 0x3,
        .clk_div.reg_offset    = TOP_CLK_RF_REG_BASE + 0x3c,
        .clk_div.mask          = 0xf00,
        .clk_gate.reg_offset   = CEN_GLB_APB_REG_BASE + 0x200,
        .clk_gate.mask         = 0x200,
    },
    {
        .name                  = "ca7_core_clk",
        .flag                  = MUX | GATE,
        .clk_config            = UNCONFIG,
        .mult_parent           = {"xtl_24m_cpu", "pll_225m_cpu",
                        "pll_600m_cpu", "pll_450m_cpu"},
        .clk_mux.reg_offset    = CPU_SYS_CLK_RF_REG_BASE + 0x20,
        .clk_mux.mask          = 0x3,
        .clk_gate.reg_offset   = CPU_SYS_AHB_REG_BASE + 0x0,
        .clk_gate.mask         = 0x1,
    },
    {
        .name                  = "arc_clk",
        .flag                  = GATE,
        .clk_config            = UNCONFIG,
        .mult_parent           = {"ca7_core_clk"},
        .clk_gate.reg_offset   = CPU_SYS_AHB_REG_BASE + 0x1c0,
        .clk_gate.mask         = 0x800000,
        .clk_gate1.reg_offset  = CPU_SYS_AHB_REG_BASE + 0x1d0,
        .clk_gate1.mask        = 0x2,
    },
    {
        .name                  = "ca7_bus_clk",
        .flag                  = DIV | GATE,
        .clk_config            = UNCONFIG,
        .mult_parent           = {"ca7_core_clk"},
        .clk_div.reg_offset    = CPU_SYS_CLK_RF_REG_BASE + 0x24,
        .clk_div.mask          = 0x700,
        .clk_gate.reg_offset   = CPU_SYS_AHB_REG_BASE + 0x0,
        .clk_gate.mask         = 0x20,
    },
    {
        .name                  = "ca7_dbg_clk",
        .flag                  = DIV,
        .clk_config            = UNCONFIG,
        .mult_parent           = {"ca7_core_clk"},
        .clk_div.reg_offset    = CPU_SYS_CLK_RF_REG_BASE + 0x28,
        .clk_div.mask          = 0x700,
    },
    {
        .name                  = "cs_dbg_clk",
        .flag                  = MUX | GATE,
        .clk_config            = UNCONFIG,
        .mult_parent           = {"xtl_24m_cpu", "pll_100m_cpu", "pll_100m_cpu"},
        .clk_mux.reg_offset    = CPU_SYS_CLK_RF_REG_BASE + 0x2c,
        .clk_mux.mask          = 0x3,
        .clk_gate.reg_offset   = CPU_SYS_AHB_REG_BASE + 0x1c0,
        .clk_gate.mask         = 0x10000000,
    },
    {
        .name                  = "i2c0_clk",
        .flag                  = MUX | DIV | GATE,
        .clk_config            = UNCONFIG,
        .mult_parent           = {"xtl_24m_cpu", "pll_50m_cpu", "pll_100m_cpu"},
        .clk_mux.reg_offset    = CPU_SYS_CLK_RF_REG_BASE + 0x38,
        .clk_mux.mask          = 0x3,
        .clk_div.reg_offset    = CPU_SYS_CLK_RF_REG_BASE + 0x38,
        .clk_div.mask          = 0x700,
        .clk_gate.reg_offset   = CPU_SYS_AHB_REG_BASE + 0xac,
        .clk_gate.mask         = 0x8,
        .clk_gate1.reg_offset  = CPU_SYS_AHB_REG_BASE + 0xb0,
        .clk_gate1.mask        = 0x20,
    },
    {
        .name                  = "i2c1_clk",
        .flag                  = MUX | DIV | GATE,
        .clk_config            = UNCONFIG,
        .mult_parent           = {"xtl_24m_cpu", "pll_50m_cpu", "pll_100m_cpu"},
        .clk_mux.reg_offset    = CPU_SYS_CLK_RF_REG_BASE + 0x3c,
        .clk_mux.mask          = 0x3,
        .clk_div.reg_offset    = CPU_SYS_CLK_RF_REG_BASE + 0x3c,
        .clk_div.mask          = 0x700,
        .clk_gate.reg_offset   = CPU_SYS_AHB_REG_BASE + 0xac,
        .clk_gate.mask         = 0x10,
        .clk_gate1.reg_offset  = CPU_SYS_AHB_REG_BASE + 0xb0,
        .clk_gate1.mask        = 0x40,
    },
    {
        .name                  = "uart0_clk",
        .flag                  = MUX | DIV | GATE,
        .clk_config            = UNCONFIG,
        .mult_parent           = {"xtl_24m_cpu", "pll_50m_cpu", "pll_100m_cpu"},
        .clk_mux.reg_offset    = CPU_SYS_CLK_RF_REG_BASE + 0x40,
        .clk_mux.mask          = 0x3,
        .clk_div.reg_offset    = CPU_SYS_CLK_RF_REG_BASE + 0x40,
        .clk_div.mask          = 0x700,
        .clk_gate.reg_offset   = CPU_SYS_AHB_REG_BASE + 0xac,
        .clk_gate.mask         = 0x200,
        .clk_gate1.reg_offset  = CPU_SYS_AHB_REG_BASE + 0xb0,
        .clk_gate1.mask        = 0x1000,
    },
    {
        .name                  = "uart1_clk",
        .flag                  = MUX | DIV | GATE,
        .clk_config            = UNCONFIG,
        .mult_parent           = {"xtl_24m_cpu", "pll_50m_cpu", "pll_100m_cpu"},
        .clk_mux.reg_offset    = CPU_SYS_CLK_RF_REG_BASE + 0x44,
        .clk_mux.mask          = 0x3,
        .clk_div.reg_offset    = CPU_SYS_CLK_RF_REG_BASE + 0x44,
        .clk_div.mask          = 0x700,
        .clk_gate.reg_offset   = CPU_SYS_AHB_REG_BASE + 0xac,
        .clk_gate.mask         = 0x400,
        .clk_gate1.reg_offset  = CPU_SYS_AHB_REG_BASE + 0xb0,
        .clk_gate1.mask        = 0x2000,
    },
    {
        .name                  = "uart2_clk",
        .flag                  = MUX | DIV | GATE,
        .clk_config            = UNCONFIG,
        .mult_parent           = {"xtl_24m_cpu", "pll_50m_cpu", "pll_100m_cpu"},
        .clk_mux.reg_offset    = CPU_SYS_CLK_RF_REG_BASE + 0x48,
        .clk_mux.mask          = 0x3,
        .clk_div.reg_offset    = CPU_SYS_CLK_RF_REG_BASE + 0x48,
        .clk_div.mask          = 0x700,
        .clk_gate.reg_offset   = CPU_SYS_AHB_REG_BASE + 0xac,
        .clk_gate.mask         = 0x800,
        .clk_gate1.reg_offset  = CPU_SYS_AHB_REG_BASE + 0xb0,
        .clk_gate1.mask        = 0x2,
    },
    {
        .name                  = "gpio_db_clk",
        .flag                  = MUX | DIV | GATE,
        .clk_config            = UNCONFIG,
        .mult_parent           = {"rtc", "pll_20m_cpu", "xtl_24m_cpu", "pll_50m_cpu"},
        .clk_mux.reg_offset    = CPU_SYS_CLK_RF_REG_BASE + 0x4c,
        .clk_mux.mask          = 0x3,
        .clk_div.reg_offset    = CPU_SYS_CLK_RF_REG_BASE + 0x4c,
        .clk_div.mask          = 0xff00,
        .clk_gate.reg_offset   = CPU_SYS_AHB_REG_BASE + 0xac,
        .clk_gate.mask         = 0x1000,
    },
    {
        .name                  = "spi1_clk",
        .flag                  = MUX | GATE,
        .clk_config            = UNCONFIG,
        .mult_parent           = {"xtl_24m_cpu", "pll_50m_cpu", "pll_100m_cpu"},
        .clk_mux.reg_offset    = CPU_SYS_CLK_RF_REG_BASE + 0x50,
        .clk_mux.mask          = 0x3,
        .clk_gate.reg_offset   = CPU_SYS_AHB_REG_BASE + 0xb0,
        .clk_gate.mask         = 0x100,
        .clk_gate1.reg_offset  = CPU_SYS_AHB_REG_BASE + 0xac,
        .clk_gate1.mask        = 0x40,
    },
    {
        .name                  = "pwm_clk",
        .flag                  = MUX | GATE,
        .clk_config            = UNCONFIG,
        .mult_parent           = {"xtl_24m_cpu", "pll_50m_cpu", "pll_100m_cpu"},
        .flag                  = MUX | GATE,
        .clk_mux.reg_offset    = CPU_SYS_CLK_RF_REG_BASE + 0x54,
        .clk_mux.mask          = 0x3,
        .clk_gate.reg_offset   = CPU_SYS_AHB_REG_BASE + 0xac,
        .clk_gate.mask         = 0x20,
        .clk_gate1.reg_offset  = CPU_SYS_AHB_REG_BASE + 0xb0,
        .clk_gate1.mask        = 0x80,
    },
    {
        .name                  = "stm0_clk",
        .flag                  = MUX | DIV | GATE,
        .clk_config            = UNCONFIG,
        .mult_parent           = {"xtl_24m_cpu", "pll_50m_cpu", "pll_100m_cpu"},
        .clk_mux.reg_offset    = CPU_SYS_CLK_RF_REG_BASE + 0x58,
        .clk_mux.mask          = 0x3,
        .clk_div.reg_offset    = CPU_SYS_CLK_RF_REG_BASE + 0x58,
        .clk_div.mask          = 0x700,
        .clk_gate.reg_offset   = CPU_SYS_AHB_REG_BASE + 0xb0,
        .clk_gate.mask         = 0x10000,
        .clk_gate1.reg_offset  = CPU_SYS_AHB_REG_BASE + 0xdc,
        .clk_gate1.mask        = 0x10000,
    },
    {
        .name                  = "stm1_clk",
        .flag                  = MUX | DIV | GATE,
        .clk_config            = UNCONFIG,
        .mult_parent           = {"xtl_24m_cpu", "pll_50m_cpu", "pll_100m_cpu"},
        .clk_mux.reg_offset    = CPU_SYS_CLK_RF_REG_BASE + 0x5c,
        .clk_mux.mask          = 0x3,
        .clk_div.reg_offset    = CPU_SYS_CLK_RF_REG_BASE + 0x5c,
        .clk_div.mask          = 0x700,
        .clk_gate.reg_offset   = CPU_SYS_AHB_REG_BASE + 0xb0,
        .clk_gate.mask         = 0x80000,
        .clk_gate.reg_offset   = CPU_SYS_AHB_REG_BASE + 0xdc,
        .clk_gate.mask         = 0x20000,
    },
    {
        .name                  = "xtl_tmr0_clk",
        .flag                  = MUX | GATE,
        .clk_config            = UNCONFIG,
        .mult_parent           = {"xtl_24m_cpu"},
        .clk_mux.reg_offset    = CPU_SYS_CLK_RF_REG_BASE + 0x60,
        .clk_mux.mask          = 0x1,
        .clk_gate.reg_offset   = CPU_SYS_AHB_REG_BASE + 0x0,
        .clk_gate.mask         = 0x10,
    },
    {
        .name                  = "rtc_tmr0_clk",
        .flag                  = MUX | GATE,
        .clk_config            = UNCONFIG,
        .mult_parent           = {"rtc"},
        .clk_mux.reg_offset    = CPU_SYS_CLK_RF_REG_BASE + 0x64,
        .clk_mux.mask          = 0x1,
        .clk_gate.reg_offset   = CPU_SYS_AHB_REG_BASE + 0x0,
        .clk_gate.mask         = 0x8,
    },
    {
        .name                  = "syst_clk",
        .flag                  = MUX | DIV | GATE,
        .clk_config            = UNCONFIG,
        .mult_parent           = {"rtc", "xtl_1m_cpu", "xtl_24m_cpu"},
        .clk_mux.reg_offset    = CPU_SYS_CLK_RF_REG_BASE + 0x68,
        .clk_mux.mask          = 0x3,
        .clk_div.reg_offset    = CPU_SYS_CLK_RF_REG_BASE + 0x68,
        .clk_div.mask          = 0xff00,
        .clk_gate.reg_offset   = CPU_SYS_AHB_REG_BASE + 0xb0,
        .clk_gate.mask         = 0x400,
    },
    {
        .name                  = "spi0_clk",
        .flag                  = MUX | DIV | GATE,
        .clk_config            = UNCONFIG,
        .mult_parent           = {"xtl_24m_cpu", "pll_180_1m_cpu",
                        "pll_200_1m_cpu", "pll_257_1m_cpu",
                        "pll_300_1m_cpu", "pll_450_1m_cpu"},
        .clk_mux.reg_offset    = CPU_SYS_CLK_RF_REG_BASE + 0x6c,
        .clk_mux.mask          = 0x7,
        .clk_div.reg_offset    = CPU_SYS_CLK_RF_REG_BASE + 0x6c,
        .clk_div.mask          = 0xff00,
        .clk_gate.reg_offset   = CPU_SYS_AHB_REG_BASE + 0xb0,
        .clk_gate.mask         = 0x8000,
        .clk_gate1.reg_offset  = CPU_SYS_AHB_REG_BASE + 0xb0,
        .clk_gate1.mask        = 0x4000,
    },
    {
        .name                  = "i2s0_slow_clk",
        .flag                  = MUX | GATE,
        .clk_config            = UNCONFIG,
        .mult_parent           = {"xtl_24m_cpu", "pll_100m_cpu", "pll_128_5m_cpu",
                    "pll_150m_cpu", "pll_200m_cpu"},
        .clk_mux.reg_offset    = CPU_SYS_AHB_REG_BASE + 0xc4,
        .clk_mux.mask          = 0x1c,
        .clk_gate.reg_offset   = CPU_SYS_AHB_REG_BASE + 0xb0,
        .clk_gate.mask         = 0x4000000,
    },
    {
        .name                  = "i2s0_fast_clk",
        .flag                  = MUX | GATE,
        .clk_config            = UNCONFIG,
        .mult_parent           = {"xtl_24m_cpu", "pll_200m_cpu", "pll_450m_cpu"},
        .clk_mux.reg_offset    = CPU_SYS_AHB_REG_BASE + 0xc4,
        .clk_mux.mask          = 0x3,
        .clk_gate.reg_offset   = CPU_SYS_AHB_REG_BASE + 0xb8,
        .clk_gate.mask         = 0x8,
    },
    {
        .name                  = "ts_24m_clk",
        .flag                  = MUX | DIV | GATE,
        .clk_config            = UNCONFIG,
        .mult_parent           = {"xtl_24m_cpu"},
        .clk_mux.reg_offset    = CPU_SYS_CLK_RF_REG_BASE + 0x70,
        .clk_mux.mask          = 0x1,
        .clk_div.reg_offset    = CPU_SYS_CLK_RF_REG_BASE + 0x70,
        .clk_div.mask          = 0xf00,
        .clk_gate.reg_offset   = CPU_SYS_AHB_REG_BASE + 0xb0,
        .clk_gate.mask         = 0x800000,
    },
    {
        .name                  = "ephy_200m_clk",
        .flag                  = MUX,
        .clk_config            = UNCONFIG,
        .mult_parent           = {"pll_200m_cpu"},
        .clk_mux.reg_offset    = CPU_SYS_CLK_RF_REG_BASE + 0x78,
        .clk_mux.mask          = 0x1,
    },
    {
        .name                  = "ephy_125m_clk",
        .flag                  = MUX | PREDIV,
        .pre_div               = 2,
        .clk_config            = UNCONFIG,
        .mult_parent           = {"pll_128_5m_cpu"},
        .clk_mux.reg_offset    = CPU_SYS_CLK_RF_REG_BASE + 0x7c,
        .clk_mux.mask          = 0x1,
    },
    {
        .name                  = "ephy_100m_clk",
        .flag                  = MUX,
        .clk_config            = UNCONFIG,
        .mult_parent           = {"pll_100m_cpu"},
        .clk_mux.reg_offset    = CPU_SYS_CLK_RF_REG_BASE + 0x80,
        .clk_mux.mask          = 0x1,
    },
    {
        .name                  = "ephy0_ref_clk",
        .flag                  = MUX | DIV | GATE,
        .clk_config            = UNCONFIG,
        .mult_parent           = {"pll_25m_cpu"},
        .clk_mux.reg_offset    = CPU_SYS_CLK_RF_REG_BASE + 0x84,
        .clk_mux.mask          = 0x1,
        .clk_div.reg_offset    = CPU_SYS_CLK_RF_REG_BASE + 0x84,
        .clk_div.mask          = 0x300,
        .clk_gate.reg_offset   = CPU_SYS_AHB_REG_BASE + 0x1fc,
        .clk_gate.mask         = 0x4,
    },
    {
        .name                  = "vou_mif_clk",
        .flag                  = MUX | DIV | GATE,
        .clk_config            = UNCONFIG,
        .mult_parent           = {"xtl_24m_cpu", "pll_225m_cpu", "pll_300m_cpu",
                    "pll_450m_cpu"},
        .clk_mux.reg_offset    = CPU_SYS_CLK_RF_REG_BASE + 0x88,
        .clk_mux.mask          = 0x3,
        .clk_div.reg_offset    = CPU_SYS_CLK_RF_REG_BASE + 0x88,
        .clk_div.mask          = 0xff00,
        .clk_gate.reg_offset   = CPU_SYS_AHB_REG_BASE + 0x1fc,
        .clk_gate.mask         = 0x2,
    },
    {
        .name                  = "efuse_clock",
        .flag                  = MUX | GATE,
        .clk_config            = UNCONFIG,
        .mult_parent           = {"xtl_24m_cpu", "pll_50m_cpu"},
        .clk_mux.reg_offset    = CPU_SYS_CLK_RF_REG_BASE + 0x8c,
        .clk_mux.mask          = 0x1,
        .clk_gate.reg_offset   = CPU_SYS_AHB_REG_BASE + 0xe0,
        .clk_gate.mask         = 0x1,
    },
    {
        .name                  = "dmic0_sr_clock",
        .flag                  = MUX,
        .clk_config            = UNCONFIG,
        .mult_parent           = {"xtl_24m_cpu", "pll_128_5m_cpu2", "pll_150m_cpu2",
                    "pll_225m_cpu2"},
        .clk_mux.reg_offset    = CPU_SYS_AHB_REG_BASE + 0x664,
        .clk_mux.mask          = 0xc00000,
    },
    {
        .name                  = "dmc_2x_clk",
        .flag                  = GATE,
        .clk_config            = UNCONFIG,
        .mult_parent           = {"ddrpll_dmc"},
        .clk_gate.reg_offset   = DMC_SYS_APB_REG_BASE + 0x300,
        .clk_gate.mask         = 0x1000,
    },
    {
        .name                  = "dmc_1x_clk",
        .flag                  = DIV | GATE,
        .clk_config            = UNCONFIG,
        .mult_parent           = {"dmc_2x_clk"},
        .clk_div.reg_offset    = DMC_SYS_APB_REG_BASE + 0x300,
        .clk_div.mask          = 0xc00,
        .clk_gate.reg_offset   = DMC_SYS_APB_REG_BASE + 0x300,
        .clk_gate.mask         = 0x10000000,
    },
    {
        .name                  = "busm_timer_clk",
        .flag                  = GATE,
        .clk_config            = UNCONFIG,
        .mult_parent           = {"xtl_24m_dmc"},
        .clk_gate.reg_offset   = DMC_SYS_APB_REG_BASE + 0x300,
        .clk_gate.mask         = 0x100000,
    },
    {
        .name                  = "isp_bus_clk",
        .flag                  = MUX | DIV | GATE,
        .clk_config            = UNCONFIG,
        .mult_parent           = {"xtl_24m_isp", "pll_100m_isp2", "pll_128_5m_isp"},
        .clk_mux.reg_offset    = ISP_SYS_APB_REG_BASE + 0x0,
        .clk_mux.mask          = 0x3000000,
        .clk_div.reg_offset    = ISP_SYS_APB_REG_BASE + 0x0,
        .clk_div.mask          = 0xf00000,
        .clk_gate.reg_offset   = ISP_SYS_APB_REG_BASE + 0x4,
        .clk_gate.mask         = 0x4000000,
    },
    {
        .name                  = "sd0_clk",
        .flag                  = MUX | GATE,
        .clk_config            = UNCONFIG,
        .mult_parent           = {"xtl_24m_isp", "pll_50m_isp"},
        .clk_mux.reg_offset    = ISP_SYS_APB_REG_BASE + 0x4,
        .clk_mux.mask          = 0x10,
        .clk_gate.reg_offset   = ISP_SYS_APB_REG_BASE + 0x4,
        .clk_gate.mask         = 0x2000000,
    },
    {
        .name                  = "ahb_sdio0_gate",
        .flag                  = GATE,
        .clk_config            = UNCONFIG,
        .clk_gate.reg_offset   = ISP_SYS_APB_REG_BASE + 0x4,
        .clk_gate.mask         = 0x40000,
    },
    {
        .name                  = "sd0_dllref_clk",
        .flag                  = GATE,
        .clk_config            = UNCONFIG,
        .mult_parent           = {"pll_100m_isp"},
        .clk_gate.reg_offset   = ISP_SYS_APB_REG_BASE + 0x4,
        .clk_gate.mask         = 0x1000000,
    },
    {
        .name                  = "sd1_clk",
        .flag                  = MUX | GATE,
        .clk_config            = UNCONFIG,
        .mult_parent           = {"xtl_24m_isp", "pll_50m_isp"},
        .clk_mux.reg_offset    = ISP_SYS_APB_REG_BASE + 0x4,
        .clk_mux.mask          = 0x8,
        .clk_gate.reg_offset   = ISP_SYS_APB_REG_BASE + 0x4,
        .clk_gate.mask         = 0x200,
    },
    {
        .name                  = "ahb_sdio1_gate",
        .flag                  = GATE,
        .clk_config            = UNCONFIG,
        .clk_gate.reg_offset   = ISP_SYS_APB_REG_BASE + 0x4,
        .clk_gate.mask         = 0x20000,
    },
    {
        .name                  = "sd1_dllref_clk",
        .flag                  = GATE,
        .clk_config            = UNCONFIG,
        .mult_parent           = {"pll_100m_isp"},
        .clk_gate.reg_offset   = ISP_SYS_APB_REG_BASE + 0x4,
        .clk_gate.mask         = 0x100,
    },
    {
        .name                  = "csi_clk",
        .flag                  = MUX | GATE,
        .clk_config            = UNCONFIG,
        .mult_parent           = {"xtl_24m_isp", "pll_50m_isp", "pll_100m_isp2",
                    "pll_100m_isp2"},
        .clk_mux.reg_offset    = ISP_SYS_APB_REG_BASE + 0x0,
        .clk_mux.mask          = 0x60000000,
        .clk_gate.reg_offset   = ISP_SYS_APB_REG_BASE + 0x0,
        .clk_gate.mask         = 0x10000000,
    },
    {
        .name                  = "vicap_clk",
        .flag                  = MUX | DIV | GATE,
        .clk_config            = UNCONFIG,
        .mult_parent           = {"xtl_24m_isp", "pll_128_5m_isp", "pll_180m_isp2"},
        .clk_mux.reg_offset    = ISP_SYS_APB_REG_BASE + 0x4,
        .clk_mux.mask          = 0xc0,
        .clk_div.reg_offset    = ISP_SYS_APB_REG_BASE + 0x0,
        .clk_div.mask          = 0x1e000,
        .clk_gate.reg_offset   = ISP_SYS_APB_REG_BASE + 0x0,
        .clk_gate.mask         = 0x40,
    },
    {
        .name                  = "veu_bus_clk",
        .flag                  = MUX | GATE,
        .clk_config            = UNCONFIG,
        .mult_parent           = {"xtl_24m_isp", "pll_64_25m_veu2", "pll_225m_veu",
                    "pll_180m_veu"},
        .clk_mux.reg_offset    = VEU_SYS_APB_REG_BASE + 0x10,
        .clk_mux.mask          = 0x30,
        .clk_gate.reg_offset   = VEU_SYS_APB_REG_BASE + 0x10,
        .clk_gate.mask         = 0x1,
    },
    {
        .name                  = "veu_clk",
        .flag                  = DIV | GATE,
        .clk_config            = UNCONFIG,
        .mult_parent           = {"veu_bus_clk"},
        .clk_div.reg_offset    = VEU_SYS_APB_REG_BASE + 0x10,
        .clk_div.mask          = 0xe,
        .clk_gate.reg_offset   = VEU_SYS_APB_REG_BASE + 0x10,
        .clk_gate.mask         = 0x80,
    },
    {
        .name                  = "usb2_ahb_clk",
        .flag                  = DIV | GATE,
        .clk_config            = UNCONFIG,
        .mult_parent           = {"veu_bus_clk"},
        .clk_div.reg_offset    = VEU_SYS_APB_REG_BASE + 0x14,
        .clk_div.mask          = 0x1c000,
        .clk_gate.reg_offset   = VEU_SYS_APB_REG_BASE + 0x10,
        .clk_gate.mask         = 0x80000,
    },
    {
        .name                  = "nn_clk",
        .flag                  = MUX | GATE,
        .clk_config            = UNCONFIG,
        .mult_parent           = {"xtl_24m_isp", "pll_180m_isp", "pll_257m",
                    "pll_300m_veu"},
        .clk_mux.reg_offset    = VEU_SYS_APB_REG_BASE + 0x10,
        .clk_mux.mask          = 0x300,
        .clk_gate.reg_offset   = VEU_SYS_APB_REG_BASE + 0x10,
        .clk_gate.mask         = 0x400,
    },
    {
        .name                  = "grp0_500m_clk",
        .flag                  = GATE,
        .clk_config            = UNCONFIG,
        .mult_parent           = {"pll_450m_veu"},
        .clk_gate.reg_offset   = VEU_SYS_APB_REG_BASE + 0x10,
        .clk_gate.mask         = 0x200000,
    },
    {
        .name                  = "grp1_500m_clk",
        .flag                  = GATE,
        .clk_config            = UNCONFIG,
        .mult_parent           = {"pll_450m_veu"},
        .clk_gate.reg_offset   = VEU_SYS_APB_REG_BASE + 0x10,
        .clk_gate.mask         = 0x400000,
    },
    {
        .name                  = "grp2_500m_clk",
        .flag                  = GATE,
        .clk_config            = UNCONFIG,
        .mult_parent           = {"pll_450m_veu"},
        .clk_gate.reg_offset   = VEU_SYS_APB_REG_BASE + 0x10,
        .clk_gate.mask         = 0x800000,
    },
    {
        .name                  = "grp0_62_5m_clk",
        .flag                  = GATE,
        .clk_config            = UNCONFIG,
        .mult_parent           = {"pll_64_25m_veu"},
        .clk_gate.reg_offset   = VEU_SYS_APB_REG_BASE + 0x10,
        .clk_gate.mask         = 0x1000000,
    },
    {
        .name                  = "grp1_62_5m_clk",
        .flag                  = GATE,
        .clk_config            = UNCONFIG,
        .mult_parent           = {"pll_64_25m_veu"},
        .clk_gate.reg_offset   = VEU_SYS_APB_REG_BASE + 0x10,
        .clk_gate.mask         = 0x2000000,
    },
    {
        .name                  = "grp2_62_5m_clk",
        .flag                  = GATE,
        .clk_config            = UNCONFIG,
        .mult_parent           = {"pll_64_25m_veu"},
        .clk_gate.reg_offset   = VEU_SYS_APB_REG_BASE + 0x10,
        .clk_gate.mask         = 0x4000000,
    },
    {
        .name                  = "grp3_62_5m_clk",
        .flag                  = GATE,
        .clk_config            = UNCONFIG,
        .mult_parent           = {"pll_64_25m_veu"},
        .clk_gate.reg_offset   = VEU_SYS_APB_REG_BASE + 0x10,
        .clk_gate.mask         = 0x8000000,
    },
    {
        .name                  = "rtc_24m_clk",
        .flag                  = GATE,
        .clk_config            = UNCONFIG,
        .mult_parent           = {"xtl_24m_veu"},
        .clk_gate.reg_offset   = VEU_SYS_APB_REG_BASE + 0x14,
        .clk_gate.mask         = 0x200,
    },
    {
        .name                  = "sadc_clk",
        .flag                  = MUX | DIV | GATE,
        .clk_config            = UNCONFIG,
        .mult_parent           = {"xtl_24m_isp", "pll_64_25m_veu", "pll_100m_veu"},
        .clk_mux.reg_offset    = VEU_SYS_APB_REG_BASE + 0x14,
        .clk_mux.mask          = 0x180,
        .clk_div.reg_offset    = VEU_SYS_APB_REG_BASE + 0x14,
        .clk_div.mask          = 0x7e,
        .clk_gate.reg_offset   = VEU_SYS_APB_REG_BASE + 0x14,
        .clk_gate.mask         = 0x1,
        .clk_gate1.reg_offset  = VEU_SYS_APB_REG_BASE + 0x14,
        .clk_gate1.mask        = 0x1000,
    },
    {
        .name                  = "acw_clk_gate",
        .flag                  = GATE,
        .clk_config            = UNCONFIG,
        .clk_gate.reg_offset   = VEU_SYS_APB_REG_BASE + 0x14,
        .clk_gate.mask         = 0x400,
    },
    {
        .name                  = "dmic_apb_gate",
        .flag                  = GATE,
        .clk_config            = UNCONFIG,
        .clk_gate.reg_offset   = CPU_SYS_AHB_REG_BASE + 0xdc,
        .clk_gate.mask         = 0x80000,
    },
    {
        .name                  = "wdt_clk",
        .flag                  = GATE,
        .clk_config            = UNCONFIG,
        .clk_gate.reg_offset   = CPU_SYS_AHB_REG_BASE + 0xb0,
        .clk_gate.mask         = 0x200,
        .clk_gate1.reg_offset  = CPU_SYS_AHB_REG_BASE + 0xb0,
        .clk_gate1.mask        = 0x10,
    },
};
struct clk fh_clk_list_high[] = {
    {
        .name                  = "osc_clk",
        .clk_out_rate          = OSC_FREQUENCY,
        .flag                  = CLOCK_FIXED,
    },
    {
        .name                  = "ddr_clk",
        .flag                  = CLOCK_DDR,
        .clk_config            = UNCONFIG,
        .clk_div.reg_offset    = CEN_GLB_APB_REG_BASE + 0x438,
        .clk_div.mask          = 0xf000007,
        .clk_div1.reg_offset   = CEN_GLB_APB_REG_BASE + 0x43c,
        .clk_div1.mask         = 0x7ff,
    },
    {
        .name                  = "pll_clk",
        .flag                  = CLOCK_PLL2 | DIV,
        .clk_config            = UNCONFIG,
        .clk_div.reg_offset    = CEN_GLB_APB_REG_BASE + 0x41c,
        .clk_div.mask          = 0x7,
        .clk_div1.reg_offset   = CEN_GLB_APB_REG_BASE + 0x420,
        .clk_div1.mask         = 0x7ff,
    },
    {
        .name                  = "pll_div2",
        .flag                  = PREDIV,
        .clk_config            = UNCONFIG,
        .mult_parent           = {"pll_clk"},
        .pre_div               = 2,

    },
    {
        .name                  = "pll_div3",
        .flag                  = PREDIV,
        .clk_config            = UNCONFIG,
        .mult_parent           = {"pll_clk"},
        .pre_div               = 3,
    },
    {
        .name                  = "pll_div7",
        .flag                  = PREDIV,
        .clk_config            = UNCONFIG,
        .mult_parent           = {"pll_clk"},
        .pre_div               = 7,
    },
    {
        .name                  = "pll_div5",
        .flag                  = PREDIV,
        .clk_config            = UNCONFIG,
        .mult_parent           = {"pll_clk"},
        .pre_div               = 5,
    },
    {
        .name                  = "pll_div72",
        .flag                  = PREDIV,
        .clk_config            = UNCONFIG,
        .mult_parent           = {"pll_clk"},
        .pre_div               = 72,
    },
    {
        .name                  = "pll_900m",
        .clk_out_rate          = 900000000,
        .flag                  = CLOCK_FIXED,
    },
    {
        .name                  = "pll_600m",
        .clk_out_rate          = 600000000,
        .flag                  = CLOCK_FIXED,
    },
    {
        .name                  = "pll_514m",
        .clk_out_rate          = 514000000,
        .flag                  = CLOCK_FIXED,
    },
    {
        .name                  = "pll_360m",
        .clk_out_rate          = 360000000,
        .flag                  = CLOCK_FIXED,
    },
    {
        .name                  = "pll_257m",
        .clk_out_rate          = 257000000,
        .flag                  = CLOCK_FIXED,
    },
    {
        .name                  = "rtc",
        .clk_out_rate          = 32768,
        .flag                  = CLOCK_FIXED,
    },
    {
        .name                  = "rtc_gate",
        .flag                  = GATE,
        .clk_config            = UNCONFIG,
        .mult_parent           = {"rtc"},
        .clk_gate.reg_offset   = VEU_SYS_APB_REG_BASE + 0x14,
        .clk_gate.mask         = 0x800,
    },
    /*top*/
    {
        .name                  = "pll_200m_top",
        .flag                  = PREDIV,
        .clk_config            = UNCONFIG,
        .mult_parent           = {"pll_600m"},
        .pre_div               = 3,
    },
    {
        .name                  = "pll_128_5m_top",
        .flag                  = PREDIV,
        .clk_config            = UNCONFIG,
        .mult_parent           = {"pll_257m"},
        .pre_div               = 2,
    },
    {
        .name                  = "pll_75m_top",
        .flag                  = PREDIV,
        .clk_config            = UNCONFIG,
        .mult_parent           = {"pll_div3"},
        .pre_div               = 8,
    },
    {
        .name                  = "pll_64_25m_top",
        .flag                  = PREDIV,
        .clk_config            = UNCONFIG,
        .mult_parent           = {"pll_div7"},
        .pre_div               = 4,
    },
    {
        .name                  = "pll_50m_top",
        .flag                  = PREDIV,
        .clk_config            = UNCONFIG,
        .mult_parent           = {"pll_div3"},
        .pre_div               = 12,
    },
    {
        .name                  = "pll_33_3m_top",
        .flag                  = PREDIV,
        .clk_config            = UNCONFIG,
        .mult_parent           = {"pll_div3"},
        .pre_div               = 18,
    },
    {
        .name                  = "pll_25m_top",
        .flag                  = PREDIV,
        .clk_config            = UNCONFIG,
        .mult_parent           = {"pll_div72"},
        .pre_div               = 1,
    },
    {
        .name                  = "xtl_24m_top",
        .flag                  = PREDIV,
        .clk_config            = UNCONFIG,
        .mult_parent           = {"osc_clk"},
        .pre_div               = 1,
    },
    /*cpu*/
    {
        .name                  = "pll_600m_cpu",
        .flag                  = PREDIV,
        .clk_config            = UNCONFIG,
        .mult_parent           = {"pll_600m"},
        .pre_div               = 1,
    },
    {
        .name                  = "pll_450m_cpu",
        .flag                  = PREDIV,
        .clk_config            = UNCONFIG,
        .mult_parent           = {"pll_900m"},
        .pre_div               = 2,
    },
    {
        .name                  = "pll_450_1m_cpu",
        .flag                  = PREDIV,
        .clk_config            = UNCONFIG,
        .mult_parent           = {"pll_div2"},
        .pre_div               = 2,
    },
    {
        .name                  = "pll_300m_cpu",
        .flag                  = PREDIV,
        .clk_config            = UNCONFIG,
        .mult_parent           = {"pll_600m"},
        .pre_div               = 2,
    },
    {
        .name                  = "pll_300_1m_cpu",
        .flag                  = PREDIV,
        .clk_config            = UNCONFIG,
        .mult_parent           = {"pll_div3"},
        .pre_div               = 2,
    },
    {
        .name                  = "pll_257m_cpu",
        .flag                  = PREDIV,
        .clk_config            = UNCONFIG,
        .mult_parent           = {"pll_257m"},
        .pre_div               = 1,
    },
    {
        .name                  = "pll_257_1m_cpu",
        .flag                  = PREDIV,
        .clk_config            = UNCONFIG,
        .mult_parent           = {"pll_div7"},
        .pre_div               = 1,
    },
    {
        .name                  = "pll_200m_cpu",
        .flag                  = PREDIV,
        .clk_config            = UNCONFIG,
        .mult_parent           = {"pll_600m"},
        .pre_div               = 3,
    },
    {
        .name                  = "pll_200_1m_cpu",
        .flag                  = PREDIV,
        .clk_config            = UNCONFIG,
        .mult_parent           = {"pll_div3"},
        .pre_div               = 3,
    },
    {
        .name                  = "pll_225m_cpu",
        .flag                  = PREDIV,
        .clk_config            = UNCONFIG,
        .mult_parent           = {"pll_900m"},
        .pre_div               = 4,
    },
    {
        .name                  = "pll_180_1m_cpu",
        .flag                  = PREDIV,
        .clk_config            = UNCONFIG,
        .mult_parent           = {"pll_div5"},
        .pre_div               = 2,
    },
    {
        .name                  = "pll_150m_cpu",
        .flag                  = PREDIV,
        .clk_config            = UNCONFIG,
        .mult_parent           = {"pll_600m"},
        .pre_div               = 4,
    },
    {
        .name                  = "pll_128_5m_cpu",
        .flag                  = PREDIV,
        .clk_config            = UNCONFIG,
        .mult_parent           = {"pll_257m"},
        .pre_div               = 2,
    },
    {
        .name                  = "pll_100m_cpu",
        .flag                  = PREDIV,
        .clk_config            = UNCONFIG,
        .mult_parent           = {"pll_div3"},
        .pre_div               = 6,
    },
    {
        .name                  = "pll_50m_cpu",
        .flag                  = PREDIV,
        .clk_config            = UNCONFIG,
        .mult_parent           = {"pll_div3"},
        .pre_div               = 12,
    },
    {
        .name                  = "pll_25m_cpu",
        .flag                  = PREDIV,
        .clk_config            = UNCONFIG,
        .mult_parent           = {"pll_div72"},
        .pre_div               = 1,
    },
    {
        .name                  = "xtl_24m_cpu",
        .flag                  = PREDIV,
        .clk_config            = UNCONFIG,
        .mult_parent           = {"osc_clk"},
        .pre_div               = 1,
    },
    {
        .name                  = "pll_20m_cpu",
        .flag                  = PREDIV,
        .clk_config            = UNCONFIG,
        .mult_parent           = {"pll_div5"},
        .pre_div               = 18,
    },
    {
        .name                  = "xtl_1m_cpu",
        .flag                  = PREDIV,
        .clk_config            = UNCONFIG,
        .mult_parent           = {"osc_clk"},
        .pre_div               = 24,
    },
    /*isp*/
    {
        .name                  = "pll_360m_isp",
        .flag                  = PREDIV,
        .clk_config            = UNCONFIG,
        .mult_parent           = {"pll_360m"},
        .pre_div               = 1,
    },
    {
        .name                  = "pll_257m_isp",
        .flag                  = PREDIV,
        .clk_config            = UNCONFIG,
        .mult_parent           = {"pll_257m"},
        .pre_div               = 1,
    },
    {
        .name                  = "pll_200m_isp",
        .flag                  = PREDIV,
        .clk_config            = UNCONFIG,
        .mult_parent           = {"pll_600m"},
        .pre_div               = 3,
    },
    {
        .name                  = "pll_180m_isp",
        .flag                  = PREDIV,
        .clk_config            = UNCONFIG,
        .mult_parent           = {"pll_360m"},
        .pre_div               = 2,
    },
    {
        .name                  = "pll_100m_isp",
        .flag                  = PREDIV,
        .clk_config            = UNCONFIG,
        .mult_parent           = {"pll_div3"},
        .pre_div               = 6,
    },
    {
        .name                  = "pll_50m_isp",
        .flag                  = PREDIV,
        .clk_config            = UNCONFIG,
        .mult_parent           = {"pll_div3"},
        .pre_div               = 12,
    },
    {
        .name                  = "xtl_24m_isp",
        .flag                  = PREDIV,
        .clk_config            = UNCONFIG,
        .mult_parent           = {"osc_clk"},
        .pre_div               = 1,
    },
    /*veu*/
    {
        .name                  = "xtl_24m_veu",
        .flag                  = PREDIV,
        .clk_config            = UNCONFIG,
        .mult_parent           = {"osc_clk"},
        .pre_div               = 1,
    },
    {
        .name                  = "pll_600m_veu",
        .flag                  = PREDIV,
        .clk_config            = UNCONFIG,
        .mult_parent           = {"pll_600m"},
        .pre_div               = 1,
    },
    {
        .name                  = "pll_514m_veu",
        .flag                  = PREDIV,
        .clk_config            = UNCONFIG,
        .mult_parent           = {"pll_514m"},
        .pre_div               = 1,
    },
    {
        .name                  = "pll_450m_veu",
        .flag                  = PREDIV,
        .clk_config            = UNCONFIG,
        .mult_parent           = {"pll_900m"},
        .pre_div               = 2,
    },
    {
        .name                  = "pll_360m_veu",
        .flag                  = PREDIV,
        .clk_config            = UNCONFIG,
        .mult_parent           = {"pll_360m"},
        .pre_div               = 1,
    },
    {
        .name                  = "pll_128_5m_veu",
        .flag                  = PREDIV,
        .clk_config            = UNCONFIG,
        .mult_parent           = {"pll_257m"},
        .pre_div               = 2,
    },
    {
        .name                  = "pll_100m_veu",
        .flag                  = PREDIV,
        .clk_config            = UNCONFIG,
        .mult_parent           = {"pll_div3"},
        .pre_div               = 6,
    },
    {
        .name                  = "pll_64_25m_veu",
        .flag                  = PREDIV,
        .clk_config            = UNCONFIG,
        .mult_parent           = {"pll_div7"},
        .pre_div               = 4,
    },
    {
        .name                  = "pll_50m_veu",
        .flag                  = PREDIV,
        .clk_config            = UNCONFIG,
        .mult_parent           = {"pll_div3"},
        .pre_div               = 12,
    },
    /*dmc*/
    {
        .name                  = "xtl_24m_dmc",
        .flag                  = PREDIV,
        .clk_config            = UNCONFIG,
        .mult_parent           = {"osc_clk"},
        .pre_div               = 1,
    },
    {
        .name                  = "pll_50m_dmc",
        .flag                  = PREDIV,
        .clk_config            = UNCONFIG,
        .mult_parent           = {"pll_div3"},
        .pre_div               = 12,
    },
    {
        .name                  = "ddrpll_dmc",
        .clk_out_rate          = 800000000,
        .flag                  = CLOCK_FIXED,
    },
    {
        .name                  = "glb_apb",
        .flag                  = MUX | DIV,
        .clk_config            = UNCONFIG,
        .mult_parent           = {"xtl_24m_top", "pll_75m_top",
                        "pll_128_5m_top", "pll_200m_top"},
        .clk_mux.reg_offset    = TOP_CLK_RF_REG_BASE + 0x20,
        .clk_mux.mask          = 0x3,
        .clk_div.reg_offset    = TOP_CLK_RF_REG_BASE + 0x20,
        .clk_div.mask          = 0x700,
    },
    {
        .name                  = "pts_clk",
        .flag                  = MUX | DIV | GATE,
        .clk_config            = UNCONFIG,
        .mult_parent           = {"xtl_24m_top", "pll_25m_top", "pll_50m_top"},
        .clk_mux.reg_offset    = TOP_CLK_RF_REG_BASE + 0x24,
        .clk_mux.mask          = 0x3,
        .clk_div.reg_offset    = TOP_CLK_RF_REG_BASE + 0x24,
        .clk_div.mask          = 0x3f00,
        .clk_gate.reg_offset   = CEN_GLB_APB_REG_BASE + 0x400,
        .clk_gate.mask         = 0x1,
    },
    {
        .name                  = "sensor0_clk",
        .flag                  = MUX | DIV | GATE,
        .clk_config            = UNCONFIG,
        .mult_parent           = {"xtl_24m_top", "pll_33_3m_top",
                        "pll_64_25m_top", "pll_75m_top"},
        .clk_mux.reg_offset    = TOP_CLK_RF_REG_BASE + 0x28,
        .clk_mux.mask          = 0x3,
        .clk_div.reg_offset    = TOP_CLK_RF_REG_BASE + 0x28,
        .clk_div.mask          = 0xf00,
        .clk_gate.reg_offset   = CEN_GLB_APB_REG_BASE + 0x400,
        .clk_gate.mask         = 0x2,
    },
    {
        .name                  = "sensor1_clk",
        .flag                  = MUX | DIV | GATE,
        .clk_config            = UNCONFIG,
        .mult_parent           = {"xtl_24m_top", "pll_33_3m_top",
                        "pll_64_25m_top", "pll_75m_top"},
        .clk_mux.reg_offset    = TOP_CLK_RF_REG_BASE + 0x2c,
        .clk_mux.mask          = 0x3,
        .clk_div.reg_offset    = TOP_CLK_RF_REG_BASE + 0x2c,
        .clk_div.mask          = 0xf00,
        .clk_gate.reg_offset   = CEN_GLB_APB_REG_BASE + 0x400,
        .clk_gate.mask         = 0x4,
    },
    {
        .name                  = "pmu_clk",
        .flag                  = MUX | DIV | GATE,
        .clk_config            = UNCONFIG,
        .mult_parent           = {"rtc", "xtl_24m_top", "pll_75m_top"},
        .clk_mux.reg_offset    = TOP_CLK_RF_REG_BASE + 0x38,
        .clk_mux.mask          = 0x3,
        .clk_div.reg_offset    = TOP_CLK_RF_REG_BASE + 0x38,
        .clk_div.mask          = 0xf00,
        .clk_gate.reg_offset   = CEN_GLB_APB_REG_BASE + 0x200,
        .clk_gate.mask         = 0x100,
    },
    {
        .name                  = "deb_clk",
        .flag                  = MUX | DIV | GATE,
        .clk_config            = UNCONFIG,
        .mult_parent           = {"rtc", "xtl_24m_top", "pll_33_3m_top",
                        "pll_75m_top"},
        .clk_mux.reg_offset    = TOP_CLK_RF_REG_BASE + 0x3c,
        .clk_mux.mask          = 0x3,
        .clk_div.reg_offset    = TOP_CLK_RF_REG_BASE + 0x3c,
        .clk_div.mask          = 0xf00,
        .clk_gate.reg_offset   = CEN_GLB_APB_REG_BASE + 0x200,
        .clk_gate.mask         = 0x200,
    },
    {
        .name                  = "ca7_core_clk",
        .flag                  = MUX | GATE,
        .clk_config            = UNCONFIG,
        .mult_parent           = {"xtl_24m_cpu", "pll_450m_cpu",
                        "pll_600m_cpu", "pll_900m"},
        .clk_mux.reg_offset    = CPU_SYS_CLK_RF_REG_BASE + 0x20,
        .clk_mux.mask          = 0x3,
        .clk_gate.reg_offset   = CPU_SYS_AHB_REG_BASE + 0x0,
        .clk_gate.mask         = 0x1,
    },
    {
        .name                  = "arc_clk",
        .flag                  = GATE,
        .clk_config            = UNCONFIG,
        .mult_parent           = {"ca7_core_clk"},
        .clk_gate.reg_offset   = CPU_SYS_AHB_REG_BASE + 0x1c0,
        .clk_gate.mask         = 0x800000,
        .clk_gate1.reg_offset  = CPU_SYS_AHB_REG_BASE + 0x1d0,
        .clk_gate1.mask        = 0x2,
    },
    {
        .name                  = "ca7_bus_clk",
        .flag                  = DIV | GATE,
        .clk_config            = UNCONFIG,
        .mult_parent           = {"ca7_core_clk"},
        .clk_div.reg_offset    = CPU_SYS_CLK_RF_REG_BASE + 0x24,
        .clk_div.mask          = 0x700,
        .clk_gate.reg_offset   = CPU_SYS_AHB_REG_BASE + 0x0,
        .clk_gate.mask         = 0x20,
    },
    {
        .name                  = "ca7_dbg_clk",
        .flag                  = DIV,
        .clk_config            = UNCONFIG,
        .mult_parent           = {"ca7_core_clk"},
        .clk_div.reg_offset    = CPU_SYS_CLK_RF_REG_BASE + 0x28,
        .clk_div.mask          = 0x700,
    },
    {
        .name                  = "cs_dbg_clk",
        .flag                  = MUX | GATE,
        .clk_config            = UNCONFIG,
        .mult_parent           = {"xtl_24m_cpu", "pll_100m_cpu", "pll_200m_cpu"},
        .clk_mux.reg_offset    = CPU_SYS_CLK_RF_REG_BASE + 0x2c,
        .clk_mux.mask          = 0x3,
        .clk_gate.reg_offset   = CPU_SYS_AHB_REG_BASE + 0x1c0,
        .clk_gate.mask         = 0x10000000,
    },
    {
        .name                  = "i2c0_clk",
        .flag                  = MUX | DIV | GATE,
        .clk_config            = UNCONFIG,
        .mult_parent           = {"xtl_24m_cpu", "pll_50m_cpu", "pll_100m_cpu"},
        .clk_mux.reg_offset    = CPU_SYS_CLK_RF_REG_BASE + 0x38,
        .clk_mux.mask          = 0x3,
        .clk_div.reg_offset    = CPU_SYS_CLK_RF_REG_BASE + 0x38,
        .clk_div.mask          = 0x700,
        .clk_gate.reg_offset   = CPU_SYS_AHB_REG_BASE + 0xac,
        .clk_gate.mask         = 0x8,
        .clk_gate1.reg_offset  = CPU_SYS_AHB_REG_BASE + 0xb0,
        .clk_gate1.mask        = 0x20,
    },
    {
        .name                  = "i2c1_clk",
        .flag                  = MUX | DIV | GATE,
        .clk_config            = UNCONFIG,
        .mult_parent           = {"xtl_24m_cpu", "pll_50m_cpu", "pll_100m_cpu"},
        .clk_mux.reg_offset    = CPU_SYS_CLK_RF_REG_BASE + 0x3c,
        .clk_mux.mask          = 0x3,
        .clk_div.reg_offset    = CPU_SYS_CLK_RF_REG_BASE + 0x3c,
        .clk_div.mask          = 0x700,
        .clk_gate.reg_offset   = CPU_SYS_AHB_REG_BASE + 0xac,
        .clk_gate.mask         = 0x10,
        .clk_gate1.reg_offset  = CPU_SYS_AHB_REG_BASE + 0xb0,
        .clk_gate1.mask        = 0x40,
    },
    {
        .name                  = "uart0_clk",
        .flag                  = MUX | DIV | GATE,
        .clk_config            = UNCONFIG,
        .mult_parent           = {"xtl_24m_cpu", "pll_50m_cpu", "pll_100m_cpu"},
        .clk_mux.reg_offset    = CPU_SYS_CLK_RF_REG_BASE + 0x40,
        .clk_mux.mask          = 0x3,
        .clk_div.reg_offset    = CPU_SYS_CLK_RF_REG_BASE + 0x40,
        .clk_div.mask          = 0x700,
        .clk_gate.reg_offset   = CPU_SYS_AHB_REG_BASE + 0xac,
        .clk_gate.mask         = 0x200,
        .clk_gate1.reg_offset  = CPU_SYS_AHB_REG_BASE + 0xb0,
        .clk_gate1.mask        = 0x1000,
    },
    {
        .name                  = "uart1_clk",
        .flag                  = MUX | DIV | GATE,
        .clk_config            = UNCONFIG,
        .mult_parent           = {"xtl_24m_cpu", "pll_50m_cpu", "pll_100m_cpu"},
        .clk_mux.reg_offset    = CPU_SYS_CLK_RF_REG_BASE + 0x44,
        .clk_mux.mask          = 0x3,
        .clk_div.reg_offset    = CPU_SYS_CLK_RF_REG_BASE + 0x44,
        .clk_div.mask          = 0x700,
        .clk_gate.reg_offset   = CPU_SYS_AHB_REG_BASE + 0xac,
        .clk_gate.mask         = 0x400,
        .clk_gate1.reg_offset  = CPU_SYS_AHB_REG_BASE + 0xb0,
        .clk_gate1.mask        = 0x2000,
    },
    {
        .name                  = "uart2_clk",
        .flag                  = MUX | DIV | GATE,
        .clk_config            = UNCONFIG,
        .mult_parent           = {"xtl_24m_cpu", "pll_50m_cpu", "pll_100m_cpu"},
        .clk_mux.reg_offset    = CPU_SYS_CLK_RF_REG_BASE + 0x48,
        .clk_mux.mask          = 0x3,
        .clk_div.reg_offset    = CPU_SYS_CLK_RF_REG_BASE + 0x48,
        .clk_div.mask          = 0x700,
        .clk_gate.reg_offset   = CPU_SYS_AHB_REG_BASE + 0xac,
        .clk_gate.mask         = 0x800,
        .clk_gate1.reg_offset  = CPU_SYS_AHB_REG_BASE + 0xb0,
        .clk_gate1.mask        = 0x2,
    },
    {
        .name                  = "gpio_db_clk",
        .flag                  = MUX | DIV | GATE,
        .clk_config            = UNCONFIG,
        .mult_parent           = {"rtc", "pll_20m_cpu", "xtl_24m_cpu", "pll_50m_cpu"},
        .clk_mux.reg_offset    = CPU_SYS_CLK_RF_REG_BASE + 0x4c,
        .clk_mux.mask          = 0x3,
        .clk_div.reg_offset    = CPU_SYS_CLK_RF_REG_BASE + 0x4c,
        .clk_div.mask          = 0xff00,
        .clk_gate.reg_offset   = CPU_SYS_AHB_REG_BASE + 0xac,
        .clk_gate.mask         = 0x1000,
    },
    {
        .name                  = "spi1_clk",
        .flag                  = MUX | GATE,
        .clk_config            = UNCONFIG,
        .mult_parent           = {"xtl_24m_cpu", "pll_50m_cpu", "pll_100m_cpu"},
        .clk_mux.reg_offset    = CPU_SYS_CLK_RF_REG_BASE + 0x50,
        .clk_mux.mask          = 0x3,
        .clk_gate.reg_offset   = CPU_SYS_AHB_REG_BASE + 0x9c,
        .clk_gate.mask         = 0x40,
        .clk_gate1.reg_offset  = CPU_SYS_AHB_REG_BASE + 0xac,
        .clk_gate1.mask        = 0x40,
    },
    {
        .name                  = "pwm_clk",
        .flag                  = MUX | GATE,
        .clk_config            = UNCONFIG,
        .mult_parent           = {"xtl_24m_cpu", "pll_50m_cpu", "pll_100m_cpu"},
        .flag                  = MUX | GATE,
        .clk_mux.reg_offset    = CPU_SYS_CLK_RF_REG_BASE + 0x54,
        .clk_mux.mask          = 0x3,
        .clk_gate.reg_offset   = CPU_SYS_AHB_REG_BASE + 0xac,
        .clk_gate.mask         = 0x20,
        .clk_gate1.reg_offset  = CPU_SYS_AHB_REG_BASE + 0xb0,
        .clk_gate1.mask        = 0x80,
    },
    {
        .name                  = "stm0_clk",
        .flag                  = MUX | DIV | GATE,
        .clk_config            = UNCONFIG,
        .mult_parent           = {"xtl_24m_cpu", "pll_50m_cpu", "pll_100m_cpu"},
        .clk_mux.reg_offset    = CPU_SYS_CLK_RF_REG_BASE + 0x58,
        .clk_mux.mask          = 0x3,
        .clk_div.reg_offset    = CPU_SYS_CLK_RF_REG_BASE + 0x58,
        .clk_div.mask          = 0x700,
        .clk_gate.reg_offset   = CPU_SYS_AHB_REG_BASE + 0xb0,
        .clk_gate.mask         = 0x10000,
        .clk_gate1.reg_offset  = CPU_SYS_AHB_REG_BASE + 0xdc,
        .clk_gate1.mask        = 0x10000,
    },
    {
        .name                  = "stm1_clk",
        .flag                  = MUX | DIV | GATE,
        .clk_config            = UNCONFIG,
        .mult_parent           = {"xtl_24m_cpu", "pll_50m_cpu", "pll_100m_cpu"},
        .clk_mux.reg_offset    = CPU_SYS_CLK_RF_REG_BASE + 0x5c,
        .clk_mux.mask          = 0x3,
        .clk_div.reg_offset    = CPU_SYS_CLK_RF_REG_BASE + 0x5c,
        .clk_div.mask          = 0x700,
        .clk_gate.reg_offset   = CPU_SYS_AHB_REG_BASE + 0xb0,
        .clk_gate.mask         = 0x80000,
        .clk_gate.reg_offset   = CPU_SYS_AHB_REG_BASE + 0xdc,
        .clk_gate.mask         = 0x20000,
    },
    {
        .name                  = "xtl_tmr0_clk",
        .flag                  = MUX | GATE,
        .clk_config            = UNCONFIG,
        .mult_parent           = {"xtl_24m_cpu"},
        .clk_mux.reg_offset    = CPU_SYS_CLK_RF_REG_BASE + 0x60,
        .clk_mux.mask          = 0x1,
        .clk_gate.reg_offset   = CPU_SYS_AHB_REG_BASE + 0x0,
        .clk_gate.mask         = 0x10,
    },
    {
        .name                  = "rtc_tmr0_clk",
        .flag                  = MUX | GATE,
        .clk_config            = UNCONFIG,
        .mult_parent           = {"rtc"},
        .clk_mux.reg_offset    = CPU_SYS_CLK_RF_REG_BASE + 0x64,
        .clk_mux.mask          = 0x1,
        .clk_gate.reg_offset   = CPU_SYS_AHB_REG_BASE + 0x0,
        .clk_gate.mask         = 0x8,
    },
    {
        .name                  = "syst_clk",
        .flag                  = MUX | DIV | GATE,
        .clk_config            = UNCONFIG,
        .mult_parent           = {"rtc", "xtl_1m_cpu", "xtl_24m_cpu"},
        .clk_mux.reg_offset    = CPU_SYS_CLK_RF_REG_BASE + 0x68,
        .clk_mux.mask          = 0x3,
        .clk_div.reg_offset    = CPU_SYS_CLK_RF_REG_BASE + 0x68,
        .clk_div.mask          = 0xff00,
        .clk_gate.reg_offset   = CPU_SYS_AHB_REG_BASE + 0xb0,
        .clk_gate.mask         = 0x400,
    },
    {
        .name                  = "spi0_clk",
        .flag                  = MUX | DIV | GATE,
        .clk_config            = UNCONFIG,
        .mult_parent           = {"xtl_24m_cpu", "pll_180_1m_cpu",
                        "pll_200_1m_cpu", "pll_257_1m_cpu",
                        "pll_300_1m_cpu", "pll_450_1m_cpu"},
        .clk_mux.reg_offset    = CPU_SYS_CLK_RF_REG_BASE + 0x6c,
        .clk_mux.mask          = 0x7,
        .clk_div.reg_offset    = CPU_SYS_CLK_RF_REG_BASE + 0x6c,
        .clk_div.mask          = 0xff00,
        .clk_gate.reg_offset   = CPU_SYS_AHB_REG_BASE + 0xb0,
        .clk_gate.mask         = 0x8000,
        .clk_gate1.reg_offset  = CPU_SYS_AHB_REG_BASE + 0xb0,
        .clk_gate1.mask        = 0x4000,
    },
    {
        .name                  = "i2s0_slow_clk",
        .flag                  = MUX | GATE,
        .clk_config            = UNCONFIG,
        .mult_parent           = {"xtl_24m_cpu", "pll_100m_cpu", "pll_128_5m_cpu",
                    "pll_150m_cpu", "pll_200m_cpu"},
        .clk_mux.reg_offset    = CPU_SYS_AHB_REG_BASE + 0xc4,
        .clk_mux.mask          = 0x1c,
        .clk_gate.reg_offset   = CPU_SYS_AHB_REG_BASE + 0xb0,
        .clk_gate.mask         = 0x4000000,
    },
    {
        .name                  = "i2s0_fast_clk",
        .flag                  = MUX | GATE,
        .clk_config            = UNCONFIG,
        .mult_parent           = {"xtl_24m_cpu", "pll_200m_cpu", "pll_450m_cpu"},
        .clk_mux.reg_offset    = CPU_SYS_AHB_REG_BASE + 0xc4,
        .clk_mux.mask          = 0x3,
        .clk_gate.reg_offset   = CPU_SYS_AHB_REG_BASE + 0xb8,
        .clk_gate.mask         = 0x8,
    },
    {
        .name                  = "ts_24m_clk",
        .flag                  = MUX | DIV | GATE,
        .clk_config            = UNCONFIG,
        .mult_parent           = {"xtl_24m_cpu"},
        .clk_mux.reg_offset    = CPU_SYS_CLK_RF_REG_BASE + 0x70,
        .clk_mux.mask          = 0x1,
        .clk_div.reg_offset    = CPU_SYS_CLK_RF_REG_BASE + 0x70,
        .clk_div.mask          = 0xf00,
        .clk_gate.reg_offset   = CPU_SYS_AHB_REG_BASE + 0xb0,
        .clk_gate.mask         = 0x800000,
    },
    {
        .name                  = "ephy_200m_clk",
        .flag                  = MUX,
        .clk_config            = UNCONFIG,
        .mult_parent           = {"pll_200m_cpu"},
        .clk_mux.reg_offset    = CPU_SYS_CLK_RF_REG_BASE + 0x78,
        .clk_mux.mask          = 0x1,
    },
    {
        .name                  = "ephy_125m_clk",
        .flag                  = MUX,
        .clk_config            = UNCONFIG,
        .mult_parent           = {"pll_128_5m_cpu"},
        .clk_mux.reg_offset    = CPU_SYS_CLK_RF_REG_BASE + 0x7c,
        .clk_mux.mask          = 0x1,
    },
    {
        .name                  = "ephy_100m_clk",
        .flag                  = MUX,
        .clk_config            = UNCONFIG,
        .mult_parent           = {"pll_100m_cpu"},
        .clk_mux.reg_offset    = CPU_SYS_CLK_RF_REG_BASE + 0x80,
        .clk_mux.mask          = 0x1,
    },
    {
        .name                  = "ephy0_ref_clk",
        .flag                  = MUX | DIV | GATE,
        .clk_config            = UNCONFIG,
        .mult_parent           = {"pll_25m_cpu"},
        .clk_mux.reg_offset    = CPU_SYS_CLK_RF_REG_BASE + 0x84,
        .clk_mux.mask          = 0x1,
        .clk_div.reg_offset    = CPU_SYS_CLK_RF_REG_BASE + 0x84,
        .clk_div.mask          = 0x300,
        .clk_gate.reg_offset   = CPU_SYS_AHB_REG_BASE + 0x1fc,
        .clk_gate.mask         = 0x4,
    },
    {
        .name                  = "vou_mif_clk",
        .flag                  = MUX | DIV | GATE,
        .clk_config            = UNCONFIG,
        .mult_parent           = {"xtl_24m_cpu", "pll_450m_cpu", "pll_600m_cpu",
                    "pll_900m"},
        .clk_mux.reg_offset    = CPU_SYS_CLK_RF_REG_BASE + 0x88,
        .clk_mux.mask          = 0x3,
        .clk_div.reg_offset    = CPU_SYS_CLK_RF_REG_BASE + 0x88,
        .clk_div.mask          = 0xff00,
        .clk_gate.reg_offset   = CPU_SYS_AHB_REG_BASE + 0x1fc,
        .clk_gate.mask         = 0x2,
    },
    {
        .name                  = "efuse_clock",
        .flag                  = MUX | GATE,
        .clk_config            = UNCONFIG,
        .mult_parent           = {"xtl_24m_cpu", "pll_50m_cpu"},
        .clk_mux.reg_offset    = CPU_SYS_CLK_RF_REG_BASE + 0x8c,
        .clk_mux.mask          = 0x1,
        .clk_gate.reg_offset   = CPU_SYS_AHB_REG_BASE + 0xe0,
        .clk_gate.mask         = 0x1,
    },
    {
        .name                  = "dmic0_sr_clock",
        .flag                  = MUX,
        .clk_config            = UNCONFIG,
        .mult_parent           = {"xtl_24m_cpu", "pll_257m_cpu", "pll_300m_cpu",
                    "pll_450m_cpu"},
        .clk_mux.reg_offset    = CPU_SYS_AHB_REG_BASE + 0x664,
        .clk_mux.mask          = 0xc00000,
    },
    {
        .name                  = "dmc_2x_clk",
        .flag                  = GATE,
        .clk_config            = UNCONFIG,
        .mult_parent           = {"ddrpll_dmc"},
        .clk_gate.reg_offset   = DMC_SYS_APB_REG_BASE + 0x300,
        .clk_gate.mask         = 0x1000,
    },
    {
        .name                  = "dmc_1x_clk",
        .flag                  = DIV | GATE,
        .clk_config            = UNCONFIG,
        .mult_parent           = {"dmc_2x_clk"},
        .clk_div.reg_offset    = DMC_SYS_APB_REG_BASE + 0x300,
        .clk_div.mask          = 0xc00,
        .clk_gate.reg_offset   = DMC_SYS_APB_REG_BASE + 0x300,
        .clk_gate.mask         = 0x10000000,
    },
    {
        .name                  = "busm_timer_clk",
        .flag                  = GATE,
        .clk_config            = UNCONFIG,
        .mult_parent           = {"xtl_24m_dmc"},
        .clk_gate.reg_offset   = DMC_SYS_APB_REG_BASE + 0x300,
        .clk_gate.mask         = 0x100000,
    },
    {
        .name                  = "isp_bus_clk",
        .flag                  = MUX | DIV | GATE,
        .clk_config            = UNCONFIG,
        .mult_parent           = {"xtl_24m_isp", "pll_200m_isp", "pll_257m_isp"},
        .clk_mux.reg_offset    = ISP_SYS_APB_REG_BASE + 0x0,
        .clk_mux.mask          = 0x3000000,
        .clk_div.reg_offset    = ISP_SYS_APB_REG_BASE + 0x0,
        .clk_div.mask          = 0xf00000,
        .clk_gate.reg_offset   = ISP_SYS_APB_REG_BASE + 0x4,
        .clk_gate.mask         = 0x4000000,
    },
    {
        .name                  = "sd0_clk",
        .flag                  = MUX | GATE,
        .clk_config            = UNCONFIG,
        .mult_parent           = {"xtl_24m_isp", "pll_50m_isp"},
        .clk_mux.reg_offset    = ISP_SYS_APB_REG_BASE + 0x4,
        .clk_mux.mask          = 0x10,
        .clk_gate.reg_offset   = ISP_SYS_APB_REG_BASE + 0x4,
        .clk_gate.mask         = 0x2000000,
    },
    {
        .name                  = "ahb_sdio0_gate",
        .flag                  = GATE,
        .clk_config            = UNCONFIG,
        .clk_gate.reg_offset   = ISP_SYS_APB_REG_BASE + 0x4,
        .clk_gate.mask         = 0x40000,
    },
    {
        .name                  = "sd0_dllref_clk",
        .flag                  = GATE,
        .clk_config            = UNCONFIG,
        .mult_parent           = {"pll_100m_isp"},
        .clk_gate.reg_offset   = ISP_SYS_APB_REG_BASE + 0x4,
        .clk_gate.mask         = 0x1000000,
    },
    {
        .name                  = "sd1_clk",
        .flag                  = MUX | GATE,
        .clk_config            = UNCONFIG,
        .mult_parent           = {"xtl_24m_isp", "pll_50m_isp"},
        .clk_mux.reg_offset    = ISP_SYS_APB_REG_BASE + 0x4,
        .clk_mux.mask          = 0x8,
        .clk_gate.reg_offset   = ISP_SYS_APB_REG_BASE + 0x4,
        .clk_gate.mask         = 0x200,
    },
    {
        .name                  = "ahb_sdio1_gate",
        .flag                  = GATE,
        .clk_config            = UNCONFIG,
        .clk_gate.reg_offset   = ISP_SYS_APB_REG_BASE + 0x4,
        .clk_gate.mask         = 0x20000,
    },
    {
        .name                  = "sd1_dllref_clk",
        .flag                  = GATE,
        .clk_config            = UNCONFIG,
        .mult_parent           = {"pll_100m_isp"},
        .clk_gate.reg_offset   = ISP_SYS_APB_REG_BASE + 0x4,
        .clk_gate.mask         = 0x100,
    },
    {
        .name                  = "csi_clk",
        .flag                  = MUX | GATE,
        .clk_config            = UNCONFIG,
        .mult_parent           = {"xtl_24m_isp", "pll_50m_isp", "pll_100m_isp",
                    "pll_200m_isp"},
        .clk_mux.reg_offset    = ISP_SYS_APB_REG_BASE + 0x0,
        .clk_mux.mask          = 0x60000000,
        .clk_gate.reg_offset   = ISP_SYS_APB_REG_BASE + 0x0,
        .clk_gate.mask         = 0x10000000,
    },
    {
        .name                  = "vicap_clk",
        .flag                  = MUX | DIV | GATE,
        .clk_config            = UNCONFIG,
        .mult_parent           = {"xtl_24m_isp", "pll_257m", "pll_360m_isp"},
        .clk_mux.reg_offset    = ISP_SYS_APB_REG_BASE + 0x4,
        .clk_mux.mask          = 0xc0,
        .clk_div.reg_offset    = ISP_SYS_APB_REG_BASE + 0x0,
        .clk_div.mask          = 0x1e000,
        .clk_gate.reg_offset   = ISP_SYS_APB_REG_BASE + 0x0,
        .clk_gate.mask         = 0x40,
    },
    {
        .name                  = "veu_bus_clk",
        .flag                  = MUX | GATE,
        .clk_config            = UNCONFIG,
        .mult_parent           = {"xtl_24m_isp", "pll_128_5m_veu", "pll_360m_veu",
                    "pll_360m_veu"},
        .clk_mux.reg_offset    = VEU_SYS_APB_REG_BASE + 0x10,
        .clk_mux.mask          = 0x30,
        .clk_gate.reg_offset   = VEU_SYS_APB_REG_BASE + 0x10,
        .clk_gate.mask         = 0x1,
    },
    {
        .name                  = "veu_clk",
        .flag                  = DIV | GATE,
        .clk_config            = UNCONFIG,
        .mult_parent           = {"veu_bus_clk"},
        .clk_div.reg_offset    = VEU_SYS_APB_REG_BASE + 0x10,
        .clk_div.mask          = 0xe,
        .clk_gate.reg_offset   = VEU_SYS_APB_REG_BASE + 0x10,
        .clk_gate.mask         = 0x80,
    },
    {
        .name                  = "usb2_ahb_clk",
        .flag                  = DIV | GATE,
        .clk_config            = UNCONFIG,
        .mult_parent           = {"veu_bus_clk"},
        .clk_div.reg_offset    = VEU_SYS_APB_REG_BASE + 0x14,
        .clk_div.mask          = 0x1c000,
        .clk_gate.reg_offset   = VEU_SYS_APB_REG_BASE + 0x10,
        .clk_gate.mask         = 0x80000,
    },
    {
        .name                  = "nn_clk",
        .flag                  = MUX | GATE,
        .clk_config            = UNCONFIG,
        .mult_parent           = {"xtl_24m_isp", "pll_360m", "pll_514m_veu",
                    "pll_514m_veu"},
        .clk_mux.reg_offset    = VEU_SYS_APB_REG_BASE + 0x10,
        .clk_mux.mask          = 0x300,
        .clk_gate.reg_offset   = VEU_SYS_APB_REG_BASE + 0x10,
        .clk_gate.mask         = 0x400,
    },
    {
        .name                  = "grp0_500m_clk",
        .flag                  = GATE,
        .clk_config            = UNCONFIG,
        .mult_parent           = {"pll_450m_veu"},
        .clk_gate.reg_offset   = VEU_SYS_APB_REG_BASE + 0x10,
        .clk_gate.mask         = 0x200000,
    },
    {
        .name                  = "grp1_500m_clk",
        .flag                  = GATE,
        .clk_config            = UNCONFIG,
        .mult_parent           = {"pll_450m_veu"},
        .clk_gate.reg_offset   = VEU_SYS_APB_REG_BASE + 0x10,
        .clk_gate.mask         = 0x400000,
    },
    {
        .name                  = "grp2_500m_clk",
        .flag                  = GATE,
        .clk_config            = UNCONFIG,
        .mult_parent           = {"pll_450m_veu"},
        .clk_gate.reg_offset   = VEU_SYS_APB_REG_BASE + 0x10,
        .clk_gate.mask         = 0x800000,
    },
    {
        .name                  = "grp0_62_5m_clk",
        .flag                  = GATE,
        .clk_config            = UNCONFIG,
        .mult_parent           = {"pll_64_25m_veu"},
        .clk_gate.reg_offset   = VEU_SYS_APB_REG_BASE + 0x10,
        .clk_gate.mask         = 0x1000000,
    },
    {
        .name                  = "grp1_62_5m_clk",
        .flag                  = GATE,
        .clk_config            = UNCONFIG,
        .mult_parent           = {"pll_64_25m_veu"},
        .clk_gate.reg_offset   = VEU_SYS_APB_REG_BASE + 0x10,
        .clk_gate.mask         = 0x2000000,
    },
    {
        .name                  = "grp2_62_5m_clk",
        .flag                  = GATE,
        .clk_config            = UNCONFIG,
        .mult_parent           = {"pll_64_25m_veu"},
        .clk_gate.reg_offset   = VEU_SYS_APB_REG_BASE + 0x10,
        .clk_gate.mask         = 0x4000000,
    },
    {
        .name                  = "grp3_62_5m_clk",
        .flag                  = GATE,
        .clk_config            = UNCONFIG,
        .mult_parent           = {"pll_64_25m_veu"},
        .clk_gate.reg_offset   = VEU_SYS_APB_REG_BASE + 0x10,
        .clk_gate.mask         = 0x8000000,
    },
    {
        .name                  = "rtc_24m_clk",
        .flag                  = GATE,
        .clk_config            = UNCONFIG,
        .mult_parent           = {"xtl_24m_veu"},
        .clk_gate.reg_offset   = VEU_SYS_APB_REG_BASE + 0x14,
        .clk_gate.mask         = 0x200,
    },
    {
        .name                  = "sadc_clk",
        .flag                  = MUX | DIV | GATE,
        .clk_config            = UNCONFIG,
        .mult_parent           = {"xtl_24m_isp", "pll_64_25m_veu", "pll_100m_veu"},
        .clk_mux.reg_offset    = VEU_SYS_APB_REG_BASE + 0x14,
        .clk_mux.mask          = 0x180,
        .clk_div.reg_offset    = VEU_SYS_APB_REG_BASE + 0x14,
        .clk_div.mask          = 0x7e,
        .clk_gate.reg_offset   = VEU_SYS_APB_REG_BASE + 0x14,
        .clk_gate.mask         = 0x1,
        .clk_gate1.reg_offset  = VEU_SYS_APB_REG_BASE + 0x14,
        .clk_gate1.mask        = 0x1000,
    },
    {
        .name                  = "acw_clk_gate",
        .flag                  = GATE,
        .clk_config            = UNCONFIG,
        .clk_gate.reg_offset   = VEU_SYS_APB_REG_BASE + 0x14,
        .clk_gate.mask         = 0x400,
    },
    {
        .name                  = "dmic_apb_gate",
        .flag                  = GATE,
        .clk_config            = UNCONFIG,
        .clk_gate.reg_offset   = CPU_SYS_AHB_REG_BASE + 0xdc,
        .clk_gate.mask         = 0x80000,
    },
    {
        .name                  = "wdt_clk",
        .flag                  = GATE,
        .clk_config            = UNCONFIG,
        .clk_gate.reg_offset   = CPU_SYS_AHB_REG_BASE + 0xb0,
        .clk_gate.mask         = 0x200,
        .clk_gate1.reg_offset  = CPU_SYS_AHB_REG_BASE + 0xb0,
        .clk_gate1.mask        = 0x10,
    },
};
unsigned int fh_clock_cfg_count_low = ARRAY_SIZE(fh_clk_list_low);
unsigned int fh_clock_cfg_count_high = ARRAY_SIZE(fh_clk_list_high);
#endif
