#ifndef __FBV__ENC_CONFIG_H__
#define __FBV__ENC_CONFIG_H__
#ifdef VIDEO_GRP0

/*  CHANNEL 0 */
#ifdef FH_CH0_OPEN_BREATH_EFFECT_G0
#define CH0_BREATH_OPEN_G0 1
#else
#define CH0_BREATH_OPEN_G0 0
#endif

#ifdef FH_CH0_USING_SAMPLE_H264_FIXQP_G0
#define CH0_RC_TYPE_G0 FH_RC_H264_FIXQP
#endif

#ifdef FH_CH0_USING_SAMPLE_H265_FIXQP_G0
#define CH0_RC_TYPE_G0 FH_RC_H265_FIXQP
#endif

#ifdef FH_CH0_USING_SAMPLE_MJPEG_FIXQP_G0
#define CH0_MJPEG_RC_TYPE_G0 FH_RC_MJPEG_FIXQP
#endif

#ifdef FH_CH0_USING_SAMPLE_H264_VBR_G0
#define CH0_RC_TYPE_G0 FH_RC_H264_VBR
#endif

#ifdef FH_CH0_USING_SAMPLE_H265_VBR_G0
#define CH0_RC_TYPE_G0 FH_RC_H265_VBR
#endif

#ifdef FH_CH0_USING_SAMPLE_MJPEG_CBR_G0
#define CH0_MJPEG_RC_TYPE_G0 FH_RC_MJPEG_CBR
#endif

#ifdef FH_CH0_USING_SAMPLE_MJPEG_VBR_G0
#define CH0_MJPEG_RC_TYPE_G0 FH_RC_MJPEG_VBR
#endif

#ifdef FH_CH0_USING_SAMPLE_H264_CBR_G0
#define CH0_RC_TYPE_G0 FH_RC_H264_CBR
#endif

#ifdef FH_CH0_USING_SAMPLE_H265_CBR_G0
#define CH0_RC_TYPE_G0 FH_RC_H265_CBR
#endif

#ifdef FH_CH0_USING_SAMPLE_H264_CVBR_G0
#define CH0_RC_TYPE_G0 FH_RC_H264_CVBR
#endif

#ifdef FH_CH0_USING_SAMPLE_H265_CVBR_G0
#define CH0_RC_TYPE_G0 FH_RC_H265_CVBR
#endif

#ifdef FH_CH0_USING_SAMPLE_H264_AVBR_G0
#define CH0_RC_TYPE_G0 FH_RC_H264_AVBR
#endif

#ifdef FH_CH0_USING_SAMPLE_H265_AVBR_G0
#define CH0_RC_TYPE_G0 FH_RC_H265_AVBR
#endif

#ifdef FH_CH0_USING_SAMPLE_H264_QVBR_G0
#define CH0_RC_TYPE_G0 FH_RC_H264_QVBR
#endif

#ifdef FH_CH0_USING_SAMPLE_H265_QVBR_G0
#define CH0_RC_TYPE_G0 FH_RC_H265_QVBR
#endif

#ifndef CH0_RC_TYPE_G0
#define CH0_RC_TYPE_G0 0xFF
#endif

/*  CHANNEL 1 */
#ifdef FH_CH1_OPEN_BREATH_EFFECT_G0
#define CH1_BREATH_OPEN_G0 1
#else
#define CH1_BREATH_OPEN_G0 0
#endif

#ifdef FH_CH1_USING_SAMPLE_H264_FIXQP_G0
#define CH1_RC_TYPE_G0 FH_RC_H264_FIXQP
#endif

#ifdef FH_CH1_USING_SAMPLE_H265_FIXQP_G0
#define CH1_RC_TYPE_G0 FH_RC_H265_FIXQP
#endif

#ifdef FH_CH1_USING_SAMPLE_MJPEG_FIXQP_G0
#define CH1_MJPEG_RC_TYPE_G0 FH_RC_MJPEG_FIXQP
#endif

#ifdef FH_CH1_USING_SAMPLE_H264_VBR_G0
#define CH1_RC_TYPE_G0 FH_RC_H264_VBR
#endif

#ifdef FH_CH1_USING_SAMPLE_H265_VBR_G0
#define CH1_RC_TYPE_G0 FH_RC_H265_VBR
#endif

#ifdef FH_CH1_USING_SAMPLE_MJPEG_CBR_G0
#define CH1_MJPEG_RC_TYPE_G0 FH_RC_MJPEG_CBR
#endif

#ifdef FH_CH1_USING_SAMPLE_MJPEG_VBR_G0
#define CH1_MJPEG_RC_TYPE_G0 FH_RC_MJPEG_VBR
#endif

#ifdef FH_CH1_USING_SAMPLE_H264_CBR_G0
#define CH1_RC_TYPE_G0 FH_RC_H264_CBR
#endif

#ifdef FH_CH1_USING_SAMPLE_H265_CBR_G0
#define CH1_RC_TYPE_G0 FH_RC_H265_CBR
#endif

#ifdef FH_CH1_USING_SAMPLE_H264_CVBR_G0
#define CH1_RC_TYPE_G0 FH_RC_H264_CVBR
#endif

#ifdef FH_CH1_USING_SAMPLE_H265_CVBR_G0
#define CH1_RC_TYPE_G0 FH_RC_H265_CVBR
#endif

#ifdef FH_CH1_USING_SAMPLE_H264_AVBR_G0
#define CH1_RC_TYPE_G0 FH_RC_H264_AVBR
#endif

#ifdef FH_CH1_USING_SAMPLE_H265_AVBR_G0
#define CH1_RC_TYPE_G0 FH_RC_H265_AVBR
#endif

#ifdef FH_CH1_USING_SAMPLE_H264_QVBR_G0
#define CH1_RC_TYPE_G0 FH_RC_H264_QVBR
#endif

#ifdef FH_CH1_USING_SAMPLE_H265_QVBR_G0
#define CH1_RC_TYPE_G0 FH_RC_H265_QVBR
#endif

#ifndef CH1_RC_TYPE_G0
#define CH1_RC_TYPE_G0 0xFF
#endif

/* CHANNLE 2 */
#ifdef FH_CH2_OPEN_BREATH_EFFECT_G0
#define CH2_BREATH_OPEN_G0 1
#else
#define CH2_BREATH_OPEN_G0 0
#endif

#ifdef FH_CH2_USING_SAMPLE_H264_FIXQP_G0
#define CH2_RC_TYPE_G0 FH_RC_H264_FIXQP
#endif

#ifdef FH_CH2_USING_SAMPLE_H265_FIXQP_G0
#define CH2_RC_TYPE_G0 FH_RC_H265_FIXQP
#endif

#ifdef FH_CH2_USING_SAMPLE_MJPEG_FIXQP_G0
#define CH2_MJPEG_RC_TYPE_G0 FH_RC_MJPEG_FIXQP
#endif

#ifdef FH_CH2_USING_SAMPLE_H264_VBR_G0
#define CH2_RC_TYPE_G0 FH_RC_H264_VBR
#endif

#ifdef FH_CH2_USING_SAMPLE_H265_VBR_G0
#define CH2_RC_TYPE_G0 FH_RC_H265_VBR
#endif

#ifdef FH_CH2_USING_SAMPLE_MJPEG_CBR_G0
#define CH2_MJPEG_RC_TYPE_G0 FH_RC_MJPEG_CBR
#endif

#ifdef FH_CH2_USING_SAMPLE_MJPEG_VBR_G0
#define CH2_MJPEG_RC_TYPE_G0 FH_RC_MJPEG_VBR
#endif

#ifdef FH_CH2_USING_SAMPLE_H264_CBR_G0
#define CH2_RC_TYPE_G0 FH_RC_H264_CBR
#endif

#ifdef FH_CH2_USING_SAMPLE_H265_CBR_G0
#define CH2_RC_TYPE_G0 FH_RC_H265_CBR
#endif

#ifdef FH_CH2_USING_SAMPLE_H264_CVBR_G0
#define CH2_RC_TYPE_G0 FH_RC_H264_CVBR
#endif

#ifdef FH_CH2_USING_SAMPLE_H265_CVBR_G0
#define CH2_RC_TYPE_G0 FH_RC_H265_CVBR
#endif

#ifdef FH_CH2_USING_SAMPLE_H264_AVBR_G0
#define CH2_RC_TYPE_G0 FH_RC_H264_AVBR
#endif

#ifdef FH_CH2_USING_SAMPLE_H265_AVBR_G0
#define CH2_RC_TYPE_G0 FH_RC_H265_AVBR
#endif

#ifdef FH_CH2_USING_SAMPLE_H264_QVBR_G0
#define CH2_RC_TYPE_G0 FH_RC_H264_QVBR
#endif

#ifdef FH_CH2_USING_SAMPLE_H265_QVBR_G0
#define CH2_RC_TYPE_G0 FH_RC_H265_QVBR
#endif

#ifndef CH2_RC_TYPE_G0
#define CH2_RC_TYPE_G0 0xFF
#endif

/* CHANNEL 3 */
#ifdef FH_CH3_OPEN_BREATH_EFFECT_G0
#define CH3_BREATH_OPEN_G0 1
#else
#define CH3_BREATH_OPEN_G0 0
#endif

#ifdef FH_CH3_USING_SAMPLE_H264_FIXQP_G0
#define CH3_RC_TYPE_G0 FH_RC_H264_FIXQP
#endif

#ifdef FH_CH3_USING_SAMPLE_H265_FIXQP_G0
#define CH3_RC_TYPE_G0 FH_RC_H265_FIXQP
#endif

#ifdef FH_CH3_USING_SAMPLE_MJPEG_FIXQP_G0
#define CH3_MJPEG_RC_TYPE_G0 FH_RC_MJPEG_FIXQP
#endif

#ifdef FH_CH3_USING_SAMPLE_H264_VBR_G0
#define CH3_RC_TYPE_G0 FH_RC_H264_VBR
#endif

#ifdef FH_CH3_USING_SAMPLE_H265_VBR_G0
#define CH3_RC_TYPE_G0 FH_RC_H265_VBR
#endif

#ifdef FH_CH3_USING_SAMPLE_MJPEG_CBR_G0
#define CH3_MJPEG_RC_TYPE_G0 FH_RC_MJPEG_CBR
#endif

#ifdef FH_CH3_USING_SAMPLE_MJPEG_VBR_G0
#define CH3_MJPEG_RC_TYPE_G0 FH_RC_MJPEG_VBR
#endif

#ifdef FH_CH3_USING_SAMPLE_H264_CBR_G0
#define CH3_RC_TYPE_G0 FH_RC_H264_CBR
#endif

#ifdef FH_CH3_USING_SAMPLE_H265_CBR_G0
#define CH3_RC_TYPE_G0 FH_RC_H265_CBR
#endif

#ifdef FH_CH3_USING_SAMPLE_H264_CVBR_G0
#define CH3_RC_TYPE_G0 FH_RC_H264_CVBR
#endif

#ifdef FH_CH3_USING_SAMPLE_H265_CVBR_G0
#define CH3_RC_TYPE_G0 FH_RC_H265_CVBR
#endif

#ifdef FH_CH3_USING_SAMPLE_H264_AVBR_G0
#define CH3_RC_TYPE_G0 FH_RC_H264_AVBR
#endif

#ifdef FH_CH3_USING_SAMPLE_H265_AVBR_G0
#define CH3_RC_TYPE_G0 FH_RC_H265_AVBR
#endif

#ifdef FH_CH3_USING_SAMPLE_H264_QVBR_G0
#define CH3_RC_TYPE_G0 FH_RC_H264_QVBR
#endif

#ifdef FH_CH3_USING_SAMPLE_H265_QVBR_G0
#define CH3_RC_TYPE_G0 FH_RC_H265_QVBR
#endif

#ifndef CH3_RC_TYPE_G0
#define CH3_RC_TYPE_G0 0xFF
#endif

/* CHANNEL 4 */
#ifdef FH_CH4_OPEN_BREATH_EFFECT_G0
#define CH4_BREATH_OPEN_G0 1
#else
#define CH4_BREATH_OPEN_G0 0
#endif

#ifdef FH_CH4_USING_SAMPLE_H264_FIXQP_G0
#define CH4_RC_TYPE_G0 FH_RC_H264_FIXQP
#endif

#ifdef FH_CH4_USING_SAMPLE_H265_FIXQP_G0
#define CH4_RC_TYPE_G0 FH_RC_H265_FIXQP
#endif

#ifdef FH_CH4_USING_SAMPLE_MJPEG_FIXQP_G0
#define CH4_MJPEG_RC_TYPE_G0 FH_RC_MJPEG_FIXQP
#endif

#ifdef FH_CH4_USING_SAMPLE_H264_VBR_G0
#define CH4_RC_TYPE_G0 FH_RC_H264_VBR
#endif

#ifdef FH_CH4_USING_SAMPLE_H265_VBR_G0
#define CH4_RC_TYPE_G0 FH_RC_H265_VBR
#endif

#ifdef FH_CH4_USING_SAMPLE_MJPEG_CBR_G0
#define CH4_MJPEG_RC_TYPE_G0 FH_RC_MJPEG_CBR
#endif

#ifdef FH_CH4_USING_SAMPLE_MJPEG_VBR_G0
#define CH4_MJPEG_RC_TYPE_G0 FH_RC_MJPEG_VBR
#endif

#ifdef FH_CH4_USING_SAMPLE_H264_CBR_G0
#define CH4_RC_TYPE_G0 FH_RC_H264_CBR
#endif

#ifdef FH_CH4_USING_SAMPLE_H265_CBR_G0
#define CH4_RC_TYPE_G0 FH_RC_H265_CBR
#endif

#ifdef FH_CH4_USING_SAMPLE_H264_CVBR_G0
#define CH4_RC_TYPE_G0 FH_RC_H264_CVBR
#endif

#ifdef FH_CH4_USING_SAMPLE_H265_CVBR_G0
#define CH4_RC_TYPE_G0 FH_RC_H265_CVBR
#endif

#ifdef FH_CH4_USING_SAMPLE_H264_AVBR_G0
#define CH4_RC_TYPE_G0 FH_RC_H264_AVBR
#endif

#ifdef FH_CH4_USING_SAMPLE_H265_AVBR_G0
#define CH4_RC_TYPE_G0 FH_RC_H265_AVBR
#endif

#ifdef FH_CH4_USING_SAMPLE_H264_QVBR_G0
#define CH4_RC_TYPE_G0 FH_RC_H264_QVBR
#endif

#ifdef FH_CH4_USING_SAMPLE_H265_QVBR_G0
#define CH4_RC_TYPE_G0 FH_RC_H265_QVBR
#endif

#ifndef CH4_RC_TYPE_G0
#define CH4_RC_TYPE_G0 0xFF
#endif

#endif /* VIDEO_GRP0 */
#ifdef VIDEO_GRP1

/*  CHANNEL 0 */
#ifdef FH_CH0_OPEN_BREATH_EFFECT_G1
#define CH0_BREATH_OPEN_G1 1
#else
#define CH0_BREATH_OPEN_G1 0
#endif

#ifdef FH_CH0_USING_SAMPLE_H264_FIXQP_G1
#define CH0_RC_TYPE_G1 FH_RC_H264_FIXQP
#endif

#ifdef FH_CH0_USING_SAMPLE_H265_FIXQP_G1
#define CH0_RC_TYPE_G1 FH_RC_H265_FIXQP
#endif

#ifdef FH_CH0_USING_SAMPLE_MJPEG_FIXQP_G1
#define CH0_MJPEG_RC_TYPE_G1 FH_RC_MJPEG_FIXQP
#endif

#ifdef FH_CH0_USING_SAMPLE_H264_VBR_G1
#define CH0_RC_TYPE_G1 FH_RC_H264_VBR
#endif

#ifdef FH_CH0_USING_SAMPLE_H265_VBR_G1
#define CH0_RC_TYPE_G1 FH_RC_H265_VBR
#endif

#ifdef FH_CH0_USING_SAMPLE_MJPEG_CBR_G1
#define CH0_MJPEG_RC_TYPE_G1 FH_RC_MJPEG_CBR
#endif

#ifdef FH_CH0_USING_SAMPLE_MJPEG_VBR_G1
#define CH0_MJPEG_RC_TYPE_G1 FH_RC_MJPEG_VBR
#endif

#ifdef FH_CH0_USING_SAMPLE_H264_CBR_G1
#define CH0_RC_TYPE_G1 FH_RC_H264_CBR
#endif

#ifdef FH_CH0_USING_SAMPLE_H265_CBR_G1
#define CH0_RC_TYPE_G1 FH_RC_H265_CBR
#endif

#ifdef FH_CH0_USING_SAMPLE_H264_CVBR_G1
#define CH0_RC_TYPE_G1 FH_RC_H264_CVBR
#endif

#ifdef FH_CH0_USING_SAMPLE_H265_CVBR_G1
#define CH0_RC_TYPE_G1 FH_RC_H265_CVBR
#endif

#ifdef FH_CH0_USING_SAMPLE_H264_AVBR_G1
#define CH0_RC_TYPE_G1 FH_RC_H264_AVBR
#endif

#ifdef FH_CH0_USING_SAMPLE_H265_AVBR_G1
#define CH0_RC_TYPE_G1 FH_RC_H265_AVBR
#endif

#ifdef FH_CH0_USING_SAMPLE_H264_QVBR_G1
#define CH0_RC_TYPE_G1 FH_RC_H264_QVBR
#endif

#ifdef FH_CH0_USING_SAMPLE_H265_QVBR_G1
#define CH0_RC_TYPE_G1 FH_RC_H265_QVBR
#endif

#ifndef CH0_RC_TYPE_G1
#define CH0_RC_TYPE_G1 0xFF
#endif

/*  CHANNEL 1 */
#ifdef FH_CH1_OPEN_BREATH_EFFECT_G1
#define CH1_BREATH_OPEN_G1 1
#else
#define CH1_BREATH_OPEN_G1 0
#endif

#ifdef FH_CH1_USING_SAMPLE_H264_FIXQP_G1
#define CH1_RC_TYPE_G1 FH_RC_H264_FIXQP
#endif

#ifdef FH_CH1_USING_SAMPLE_H265_FIXQP_G1
#define CH1_RC_TYPE_G1 FH_RC_H265_FIXQP
#endif

#ifdef FH_CH1_USING_SAMPLE_MJPEG_FIXQP_G1
#define CH1_MJPEG_RC_TYPE_G1 FH_RC_MJPEG_FIXQP
#endif

#ifdef FH_CH1_USING_SAMPLE_H264_VBR_G1
#define CH1_RC_TYPE_G1 FH_RC_H264_VBR
#endif

#ifdef FH_CH1_USING_SAMPLE_H265_VBR_G1
#define CH1_RC_TYPE_G1 FH_RC_H265_VBR
#endif

#ifdef FH_CH1_USING_SAMPLE_MJPEG_CBR_G1
#define CH1_MJPEG_RC_TYPE_G1 FH_RC_MJPEG_CBR
#endif

#ifdef FH_CH1_USING_SAMPLE_MJPEG_VBR_G1
#define CH1_MJPEG_RC_TYPE_G1 FH_RC_MJPEG_VBR
#endif

#ifdef FH_CH1_USING_SAMPLE_H264_CBR_G1
#define CH1_RC_TYPE_G1 FH_RC_H264_CBR
#endif

#ifdef FH_CH1_USING_SAMPLE_H265_CBR_G1
#define CH1_RC_TYPE_G1 FH_RC_H265_CBR
#endif

#ifdef FH_CH1_USING_SAMPLE_H264_CVBR_G1
#define CH1_RC_TYPE_G1 FH_RC_H264_CVBR
#endif

#ifdef FH_CH1_USING_SAMPLE_H265_CVBR_G1
#define CH1_RC_TYPE_G1 FH_RC_H265_CVBR
#endif

#ifdef FH_CH1_USING_SAMPLE_H264_AVBR_G1
#define CH1_RC_TYPE_G1 FH_RC_H264_AVBR
#endif

#ifdef FH_CH1_USING_SAMPLE_H265_AVBR_G1
#define CH1_RC_TYPE_G1 FH_RC_H265_AVBR
#endif

#ifdef FH_CH1_USING_SAMPLE_H264_QVBR_G1
#define CH1_RC_TYPE_G1 FH_RC_H264_QVBR
#endif

#ifdef FH_CH1_USING_SAMPLE_H265_QVBR_G1
#define CH1_RC_TYPE_G1 FH_RC_H265_QVBR
#endif

#ifndef CH1_RC_TYPE_G1
#define CH1_RC_TYPE_G1 0xFF
#endif

/* CHANNLE 2 */
#ifdef FH_CH2_OPEN_BREATH_EFFECT_G1
#define CH2_BREATH_OPEN_G1 1
#else
#define CH2_BREATH_OPEN_G1 0
#endif

#ifdef FH_CH2_USING_SAMPLE_H264_FIXQP_G1
#define CH2_RC_TYPE_G1 FH_RC_H264_FIXQP
#endif

#ifdef FH_CH2_USING_SAMPLE_H265_FIXQP_G1
#define CH2_RC_TYPE_G1 FH_RC_H265_FIXQP
#endif

#ifdef FH_CH2_USING_SAMPLE_MJPEG_FIXQP_G1
#define CH2_MJPEG_RC_TYPE_G1 FH_RC_MJPEG_FIXQP
#endif

#ifdef FH_CH2_USING_SAMPLE_H264_VBR_G1
#define CH2_RC_TYPE_G1 FH_RC_H264_VBR
#endif

#ifdef FH_CH2_USING_SAMPLE_H265_VBR_G1
#define CH2_RC_TYPE_G1 FH_RC_H265_VBR
#endif

#ifdef FH_CH2_USING_SAMPLE_MJPEG_CBR_G1
#define CH2_MJPEG_RC_TYPE_G1 FH_RC_MJPEG_CBR
#endif

#ifdef FH_CH2_USING_SAMPLE_MJPEG_VBR_G1
#define CH2_MJPEG_RC_TYPE_G1 FH_RC_MJPEG_VBR
#endif

#ifdef FH_CH2_USING_SAMPLE_H264_CBR_G1
#define CH2_RC_TYPE_G1 FH_RC_H264_CBR
#endif

#ifdef FH_CH2_USING_SAMPLE_H265_CBR_G1
#define CH2_RC_TYPE_G1 FH_RC_H265_CBR
#endif

#ifdef FH_CH2_USING_SAMPLE_H264_CVBR_G1
#define CH2_RC_TYPE_G1 FH_RC_H264_CVBR
#endif

#ifdef FH_CH2_USING_SAMPLE_H265_CVBR_G1
#define CH2_RC_TYPE_G1 FH_RC_H265_CVBR
#endif

#ifdef FH_CH2_USING_SAMPLE_H264_AVBR_G1
#define CH2_RC_TYPE_G1 FH_RC_H264_AVBR
#endif

#ifdef FH_CH2_USING_SAMPLE_H265_AVBR_G1
#define CH2_RC_TYPE_G1 FH_RC_H265_AVBR
#endif

#ifdef FH_CH2_USING_SAMPLE_H264_QVBR_G1
#define CH2_RC_TYPE_G1 FH_RC_H264_QVBR
#endif

#ifdef FH_CH2_USING_SAMPLE_H265_QVBR_G1
#define CH2_RC_TYPE_G1 FH_RC_H265_QVBR
#endif

#ifndef CH2_RC_TYPE_G1
#define CH2_RC_TYPE_G1 0xFF
#endif

/* CHANNEL 3 */
#ifdef FH_CH3_OPEN_BREATH_EFFECT_G1
#define CH3_BREATH_OPEN_G1 1
#else
#define CH3_BREATH_OPEN_G1 0
#endif

#ifdef FH_CH3_USING_SAMPLE_H264_FIXQP_G1
#define CH3_RC_TYPE_G1 FH_RC_H264_FIXQP
#endif

#ifdef FH_CH3_USING_SAMPLE_H265_FIXQP_G1
#define CH3_RC_TYPE_G1 FH_RC_H265_FIXQP
#endif

#ifdef FH_CH3_USING_SAMPLE_MJPEG_FIXQP_G1
#define CH3_MJPEG_RC_TYPE_G1 FH_RC_MJPEG_FIXQP
#endif

#ifdef FH_CH3_USING_SAMPLE_H264_VBR_G1
#define CH3_RC_TYPE_G1 FH_RC_H264_VBR
#endif

#ifdef FH_CH3_USING_SAMPLE_H265_VBR_G1
#define CH3_RC_TYPE_G1 FH_RC_H265_VBR
#endif

#ifdef FH_CH3_USING_SAMPLE_MJPEG_CBR_G1
#define CH3_MJPEG_RC_TYPE_G1 FH_RC_MJPEG_CBR
#endif

#ifdef FH_CH3_USING_SAMPLE_MJPEG_VBR_G1
#define CH3_MJPEG_RC_TYPE_G1 FH_RC_MJPEG_VBR
#endif

#ifdef FH_CH3_USING_SAMPLE_H264_CBR_G1
#define CH3_RC_TYPE_G1 FH_RC_H264_CBR
#endif

#ifdef FH_CH3_USING_SAMPLE_H265_CBR_G1
#define CH3_RC_TYPE_G1 FH_RC_H265_CBR
#endif

#ifdef FH_CH3_USING_SAMPLE_H264_CVBR_G1
#define CH3_RC_TYPE_G1 FH_RC_H264_CVBR
#endif

#ifdef FH_CH3_USING_SAMPLE_H265_CVBR_G1
#define CH3_RC_TYPE_G1 FH_RC_H265_CVBR
#endif

#ifdef FH_CH3_USING_SAMPLE_H264_AVBR_G1
#define CH3_RC_TYPE_G1 FH_RC_H264_AVBR
#endif

#ifdef FH_CH3_USING_SAMPLE_H265_AVBR_G1
#define CH3_RC_TYPE_G1 FH_RC_H265_AVBR
#endif

#ifdef FH_CH3_USING_SAMPLE_H264_QVBR_G1
#define CH3_RC_TYPE_G1 FH_RC_H264_QVBR
#endif

#ifdef FH_CH3_USING_SAMPLE_H265_QVBR_G1
#define CH3_RC_TYPE_G1 FH_RC_H265_QVBR
#endif

#ifndef CH3_RC_TYPE_G1
#define CH3_RC_TYPE_G1 0xFF
#endif

/* CHANNEL 4 */
#ifdef FH_CH4_OPEN_BREATH_EFFECT_G1
#define CH4_BREATH_OPEN_G1 1
#else
#define CH4_BREATH_OPEN_G1 0
#endif

#ifdef FH_CH4_USING_SAMPLE_H264_FIXQP_G1
#define CH4_RC_TYPE_G1 FH_RC_H264_FIXQP
#endif

#ifdef FH_CH4_USING_SAMPLE_H265_FIXQP_G1
#define CH4_RC_TYPE_G1 FH_RC_H265_FIXQP
#endif

#ifdef FH_CH4_USING_SAMPLE_MJPEG_FIXQP_G1
#define CH4_MJPEG_RC_TYPE_G1 FH_RC_MJPEG_FIXQP
#endif

#ifdef FH_CH4_USING_SAMPLE_H264_VBR_G1
#define CH4_RC_TYPE_G1 FH_RC_H264_VBR
#endif

#ifdef FH_CH4_USING_SAMPLE_H265_VBR_G1
#define CH4_RC_TYPE_G1 FH_RC_H265_VBR
#endif

#ifdef FH_CH4_USING_SAMPLE_MJPEG_CBR_G1
#define CH4_MJPEG_RC_TYPE_G1 FH_RC_MJPEG_CBR
#endif

#ifdef FH_CH4_USING_SAMPLE_MJPEG_VBR_G1
#define CH4_MJPEG_RC_TYPE_G1 FH_RC_MJPEG_VBR
#endif

#ifdef FH_CH4_USING_SAMPLE_H264_CBR_G1
#define CH4_RC_TYPE_G1 FH_RC_H264_CBR
#endif

#ifdef FH_CH4_USING_SAMPLE_H265_CBR_G1
#define CH4_RC_TYPE_G1 FH_RC_H265_CBR
#endif

#ifdef FH_CH4_USING_SAMPLE_H264_CVBR_G1
#define CH4_RC_TYPE_G1 FH_RC_H264_CVBR
#endif

#ifdef FH_CH4_USING_SAMPLE_H265_CVBR_G1
#define CH4_RC_TYPE_G1 FH_RC_H265_CVBR
#endif

#ifdef FH_CH4_USING_SAMPLE_H264_AVBR_G1
#define CH4_RC_TYPE_G1 FH_RC_H264_AVBR
#endif

#ifdef FH_CH4_USING_SAMPLE_H265_AVBR_G1
#define CH4_RC_TYPE_G1 FH_RC_H265_AVBR
#endif

#ifdef FH_CH4_USING_SAMPLE_H264_QVBR_G1
#define CH4_RC_TYPE_G1 FH_RC_H264_QVBR
#endif

#ifdef FH_CH4_USING_SAMPLE_H265_QVBR_G1
#define CH4_RC_TYPE_G1 FH_RC_H265_QVBR
#endif

#ifndef CH4_RC_TYPE_G1
#define CH4_RC_TYPE_G1 0xFF
#endif

#endif /* VIDEO_GRP1 */
#ifdef VIDEO_GRP2

/*  CHANNEL 0 */
#ifdef FH_CH0_OPEN_BREATH_EFFECT_G2
#define CH0_BREATH_OPEN_G2 1
#else
#define CH0_BREATH_OPEN_G2 0
#endif

#ifdef FH_CH0_USING_SAMPLE_H264_FIXQP_G2
#define CH0_RC_TYPE_G2 FH_RC_H264_FIXQP
#endif

#ifdef FH_CH0_USING_SAMPLE_H265_FIXQP_G2
#define CH0_RC_TYPE_G2 FH_RC_H265_FIXQP
#endif

#ifdef FH_CH0_USING_SAMPLE_MJPEG_FIXQP_G2
#define CH0_MJPEG_RC_TYPE_G2 FH_RC_MJPEG_FIXQP
#endif

#ifdef FH_CH0_USING_SAMPLE_H264_VBR_G2
#define CH0_RC_TYPE_G2 FH_RC_H264_VBR
#endif

#ifdef FH_CH0_USING_SAMPLE_H265_VBR_G2
#define CH0_RC_TYPE_G2 FH_RC_H265_VBR
#endif

#ifdef FH_CH0_USING_SAMPLE_MJPEG_CBR_G2
#define CH0_MJPEG_RC_TYPE_G2 FH_RC_MJPEG_CBR
#endif

#ifdef FH_CH0_USING_SAMPLE_MJPEG_VBR_G2
#define CH0_MJPEG_RC_TYPE_G2 FH_RC_MJPEG_VBR
#endif

#ifdef FH_CH0_USING_SAMPLE_H264_CBR_G2
#define CH0_RC_TYPE_G2 FH_RC_H264_CBR
#endif

#ifdef FH_CH0_USING_SAMPLE_H265_CBR_G2
#define CH0_RC_TYPE_G2 FH_RC_H265_CBR
#endif

#ifdef FH_CH0_USING_SAMPLE_H264_CVBR_G2
#define CH0_RC_TYPE_G2 FH_RC_H264_CVBR
#endif

#ifdef FH_CH0_USING_SAMPLE_H265_CVBR_G2
#define CH0_RC_TYPE_G2 FH_RC_H265_CVBR
#endif

#ifdef FH_CH0_USING_SAMPLE_H264_AVBR_G2
#define CH0_RC_TYPE_G2 FH_RC_H264_AVBR
#endif

#ifdef FH_CH0_USING_SAMPLE_H265_AVBR_G2
#define CH0_RC_TYPE_G2 FH_RC_H265_AVBR
#endif

#ifdef FH_CH0_USING_SAMPLE_H264_QVBR_G2
#define CH0_RC_TYPE_G2 FH_RC_H264_QVBR
#endif

#ifdef FH_CH0_USING_SAMPLE_H265_QVBR_G2
#define CH0_RC_TYPE_G2 FH_RC_H265_QVBR
#endif

#ifndef CH0_RC_TYPE_G2
#define CH0_RC_TYPE_G2 0xFF
#endif

/*  CHANNEL 1 */
#ifdef FH_CH1_OPEN_BREATH_EFFECT_G2
#define CH1_BREATH_OPEN_G2 1
#else
#define CH1_BREATH_OPEN_G2 0
#endif

#ifdef FH_CH1_USING_SAMPLE_H264_FIXQP_G2
#define CH1_RC_TYPE_G2 FH_RC_H264_FIXQP
#endif

#ifdef FH_CH1_USING_SAMPLE_H265_FIXQP_G2
#define CH1_RC_TYPE_G2 FH_RC_H265_FIXQP
#endif

#ifdef FH_CH1_USING_SAMPLE_MJPEG_FIXQP_G2
#define CH1_MJPEG_RC_TYPE_G2 FH_RC_MJPEG_FIXQP
#endif

#ifdef FH_CH1_USING_SAMPLE_H264_VBR_G2
#define CH1_RC_TYPE_G2 FH_RC_H264_VBR
#endif

#ifdef FH_CH1_USING_SAMPLE_H265_VBR_G2
#define CH1_RC_TYPE_G2 FH_RC_H265_VBR
#endif

#ifdef FH_CH1_USING_SAMPLE_MJPEG_CBR_G2
#define CH1_MJPEG_RC_TYPE_G2 FH_RC_MJPEG_CBR
#endif

#ifdef FH_CH1_USING_SAMPLE_MJPEG_VBR_G2
#define CH1_MJPEG_RC_TYPE_G2 FH_RC_MJPEG_VBR
#endif

#ifdef FH_CH1_USING_SAMPLE_H264_CBR_G2
#define CH1_RC_TYPE_G2 FH_RC_H264_CBR
#endif

#ifdef FH_CH1_USING_SAMPLE_H265_CBR_G2
#define CH1_RC_TYPE_G2 FH_RC_H265_CBR
#endif

#ifdef FH_CH1_USING_SAMPLE_H264_CVBR_G2
#define CH1_RC_TYPE_G2 FH_RC_H264_CVBR
#endif

#ifdef FH_CH1_USING_SAMPLE_H265_CVBR_G2
#define CH1_RC_TYPE_G2 FH_RC_H265_CVBR
#endif

#ifdef FH_CH1_USING_SAMPLE_H264_AVBR_G2
#define CH1_RC_TYPE_G2 FH_RC_H264_AVBR
#endif

#ifdef FH_CH1_USING_SAMPLE_H265_AVBR_G2
#define CH1_RC_TYPE_G2 FH_RC_H265_AVBR
#endif

#ifdef FH_CH1_USING_SAMPLE_H264_QVBR_G2
#define CH1_RC_TYPE_G2 FH_RC_H264_QVBR
#endif

#ifdef FH_CH1_USING_SAMPLE_H265_QVBR_G2
#define CH1_RC_TYPE_G2 FH_RC_H265_QVBR
#endif

#ifndef CH1_RC_TYPE_G2
#define CH1_RC_TYPE_G2 0xFF
#endif

/* CHANNLE 2 */
#ifdef FH_CH2_OPEN_BREATH_EFFECT_G2
#define CH2_BREATH_OPEN_G2 1
#else
#define CH2_BREATH_OPEN_G2 0
#endif

#ifdef FH_CH2_USING_SAMPLE_H264_FIXQP_G2
#define CH2_RC_TYPE_G2 FH_RC_H264_FIXQP
#endif

#ifdef FH_CH2_USING_SAMPLE_H265_FIXQP_G2
#define CH2_RC_TYPE_G2 FH_RC_H265_FIXQP
#endif

#ifdef FH_CH2_USING_SAMPLE_MJPEG_FIXQP_G2
#define CH2_MJPEG_RC_TYPE_G2 FH_RC_MJPEG_FIXQP
#endif

#ifdef FH_CH2_USING_SAMPLE_H264_VBR_G2
#define CH2_RC_TYPE_G2 FH_RC_H264_VBR
#endif

#ifdef FH_CH2_USING_SAMPLE_H265_VBR_G2
#define CH2_RC_TYPE_G2 FH_RC_H265_VBR
#endif

#ifdef FH_CH2_USING_SAMPLE_MJPEG_CBR_G2
#define CH2_MJPEG_RC_TYPE_G2 FH_RC_MJPEG_CBR
#endif

#ifdef FH_CH2_USING_SAMPLE_MJPEG_VBR_G2
#define CH2_MJPEG_RC_TYPE_G2 FH_RC_MJPEG_VBR
#endif

#ifdef FH_CH2_USING_SAMPLE_H264_CBR_G2
#define CH2_RC_TYPE_G2 FH_RC_H264_CBR
#endif

#ifdef FH_CH2_USING_SAMPLE_H265_CBR_G2
#define CH2_RC_TYPE_G2 FH_RC_H265_CBR
#endif

#ifdef FH_CH2_USING_SAMPLE_H264_CVBR_G2
#define CH2_RC_TYPE_G2 FH_RC_H264_CVBR
#endif

#ifdef FH_CH2_USING_SAMPLE_H265_CVBR_G2
#define CH2_RC_TYPE_G2 FH_RC_H265_CVBR
#endif

#ifdef FH_CH2_USING_SAMPLE_H264_AVBR_G2
#define CH2_RC_TYPE_G2 FH_RC_H264_AVBR
#endif

#ifdef FH_CH2_USING_SAMPLE_H265_AVBR_G2
#define CH2_RC_TYPE_G2 FH_RC_H265_AVBR
#endif

#ifdef FH_CH2_USING_SAMPLE_H264_QVBR_G2
#define CH2_RC_TYPE_G2 FH_RC_H264_QVBR
#endif

#ifdef FH_CH2_USING_SAMPLE_H265_QVBR_G2
#define CH2_RC_TYPE_G2 FH_RC_H265_QVBR
#endif

#ifndef CH2_RC_TYPE_G2
#define CH2_RC_TYPE_G2 0xFF
#endif

/* CHANNEL 3 */
#ifdef FH_CH3_OPEN_BREATH_EFFECT_G2
#define CH3_BREATH_OPEN_G2 1
#else
#define CH3_BREATH_OPEN_G2 0
#endif

#ifdef FH_CH3_USING_SAMPLE_H264_FIXQP_G2
#define CH3_RC_TYPE_G2 FH_RC_H264_FIXQP
#endif

#ifdef FH_CH3_USING_SAMPLE_H265_FIXQP_G2
#define CH3_RC_TYPE_G2 FH_RC_H265_FIXQP
#endif

#ifdef FH_CH3_USING_SAMPLE_MJPEG_FIXQP_G2
#define CH3_MJPEG_RC_TYPE_G2 FH_RC_MJPEG_FIXQP
#endif

#ifdef FH_CH3_USING_SAMPLE_H264_VBR_G2
#define CH3_RC_TYPE_G2 FH_RC_H264_VBR
#endif

#ifdef FH_CH3_USING_SAMPLE_H265_VBR_G2
#define CH3_RC_TYPE_G2 FH_RC_H265_VBR
#endif

#ifdef FH_CH3_USING_SAMPLE_MJPEG_CBR_G2
#define CH3_MJPEG_RC_TYPE_G2 FH_RC_MJPEG_CBR
#endif

#ifdef FH_CH3_USING_SAMPLE_MJPEG_VBR_G2
#define CH3_MJPEG_RC_TYPE_G2 FH_RC_MJPEG_VBR
#endif

#ifdef FH_CH3_USING_SAMPLE_H264_CBR_G2
#define CH3_RC_TYPE_G2 FH_RC_H264_CBR
#endif

#ifdef FH_CH3_USING_SAMPLE_H265_CBR_G2
#define CH3_RC_TYPE_G2 FH_RC_H265_CBR
#endif

#ifdef FH_CH3_USING_SAMPLE_H264_CVBR_G2
#define CH3_RC_TYPE_G2 FH_RC_H264_CVBR
#endif

#ifdef FH_CH3_USING_SAMPLE_H265_CVBR_G2
#define CH3_RC_TYPE_G2 FH_RC_H265_CVBR
#endif

#ifdef FH_CH3_USING_SAMPLE_H264_AVBR_G2
#define CH3_RC_TYPE_G2 FH_RC_H264_AVBR
#endif

#ifdef FH_CH3_USING_SAMPLE_H265_AVBR_G2
#define CH3_RC_TYPE_G2 FH_RC_H265_AVBR
#endif

#ifdef FH_CH3_USING_SAMPLE_H264_QVBR_G2
#define CH3_RC_TYPE_G2 FH_RC_H264_QVBR
#endif

#ifdef FH_CH3_USING_SAMPLE_H265_QVBR_G2
#define CH3_RC_TYPE_G2 FH_RC_H265_QVBR
#endif

#ifndef CH3_RC_TYPE_G2
#define CH3_RC_TYPE_G2 0xFF
#endif

/* CHANNEL 4 */
#ifdef FH_CH4_OPEN_BREATH_EFFECT_G2
#define CH4_BREATH_OPEN_G2 1
#else
#define CH4_BREATH_OPEN_G2 0
#endif

#ifdef FH_CH4_USING_SAMPLE_H264_FIXQP_G2
#define CH4_RC_TYPE_G2 FH_RC_H264_FIXQP
#endif

#ifdef FH_CH4_USING_SAMPLE_H265_FIXQP_G2
#define CH4_RC_TYPE_G2 FH_RC_H265_FIXQP
#endif

#ifdef FH_CH4_USING_SAMPLE_MJPEG_FIXQP_G2
#define CH4_MJPEG_RC_TYPE_G2 FH_RC_MJPEG_FIXQP
#endif

#ifdef FH_CH4_USING_SAMPLE_H264_VBR_G2
#define CH4_RC_TYPE_G2 FH_RC_H264_VBR
#endif

#ifdef FH_CH4_USING_SAMPLE_H265_VBR_G2
#define CH4_RC_TYPE_G2 FH_RC_H265_VBR
#endif

#ifdef FH_CH4_USING_SAMPLE_MJPEG_CBR_G2
#define CH4_MJPEG_RC_TYPE_G2 FH_RC_MJPEG_CBR
#endif

#ifdef FH_CH4_USING_SAMPLE_MJPEG_VBR_G2
#define CH4_MJPEG_RC_TYPE_G2 FH_RC_MJPEG_VBR
#endif

#ifdef FH_CH4_USING_SAMPLE_H264_CBR_G2
#define CH4_RC_TYPE_G2 FH_RC_H264_CBR
#endif

#ifdef FH_CH4_USING_SAMPLE_H265_CBR_G2
#define CH4_RC_TYPE_G2 FH_RC_H265_CBR
#endif

#ifdef FH_CH4_USING_SAMPLE_H264_CVBR_G2
#define CH4_RC_TYPE_G2 FH_RC_H264_CVBR
#endif

#ifdef FH_CH4_USING_SAMPLE_H265_CVBR_G2
#define CH4_RC_TYPE_G2 FH_RC_H265_CVBR
#endif

#ifdef FH_CH4_USING_SAMPLE_H264_AVBR_G2
#define CH4_RC_TYPE_G2 FH_RC_H264_AVBR
#endif

#ifdef FH_CH4_USING_SAMPLE_H265_AVBR_G2
#define CH4_RC_TYPE_G2 FH_RC_H265_AVBR
#endif

#ifdef FH_CH4_USING_SAMPLE_H264_QVBR_G2
#define CH4_RC_TYPE_G2 FH_RC_H264_QVBR
#endif

#ifdef FH_CH4_USING_SAMPLE_H265_QVBR_G2
#define CH4_RC_TYPE_G2 FH_RC_H265_QVBR
#endif

#ifndef CH4_RC_TYPE_G2
#define CH4_RC_TYPE_G2 0xFF
#endif

#endif /* VIDEO_GRP2 */
#ifdef VDEC_SEND_G3

/*  CHANNEL 0 */
#ifdef FH_CH0_OPEN_BREATH_EFFECT_G3
#define CH0_BREATH_OPEN_G3 1
#else
#define CH0_BREATH_OPEN_G3 0
#endif

#ifdef FH_CH0_USING_SAMPLE_H264_FIXQP_G3
#define CH0_RC_TYPE_G3 FH_RC_H264_FIXQP
#endif

#ifdef FH_CH0_USING_SAMPLE_H265_FIXQP_G3
#define CH0_RC_TYPE_G3 FH_RC_H265_FIXQP
#endif

#ifdef FH_CH0_USING_SAMPLE_MJPEG_FIXQP_G3
#define CH0_MJPEG_RC_TYPE_G3 FH_RC_MJPEG_FIXQP
#endif

#ifdef FH_CH0_USING_SAMPLE_H264_VBR_G3
#define CH0_RC_TYPE_G3 FH_RC_H264_VBR
#endif

#ifdef FH_CH0_USING_SAMPLE_H265_VBR_G3
#define CH0_RC_TYPE_G3 FH_RC_H265_VBR
#endif

#ifdef FH_CH0_USING_SAMPLE_MJPEG_CBR_G3
#define CH0_MJPEG_RC_TYPE_G3 FH_RC_MJPEG_CBR
#endif

#ifdef FH_CH0_USING_SAMPLE_MJPEG_VBR_G3
#define CH0_MJPEG_RC_TYPE_G3 FH_RC_MJPEG_VBR
#endif

#ifdef FH_CH0_USING_SAMPLE_H264_CBR_G3
#define CH0_RC_TYPE_G3 FH_RC_H264_CBR
#endif

#ifdef FH_CH0_USING_SAMPLE_H265_CBR_G3
#define CH0_RC_TYPE_G3 FH_RC_H265_CBR
#endif

#ifdef FH_CH0_USING_SAMPLE_H264_CVBR_G3
#define CH0_RC_TYPE_G3 FH_RC_H264_CVBR
#endif

#ifdef FH_CH0_USING_SAMPLE_H265_CVBR_G3
#define CH0_RC_TYPE_G3 FH_RC_H265_CVBR
#endif

#ifdef FH_CH0_USING_SAMPLE_H264_AVBR_G3
#define CH0_RC_TYPE_G3 FH_RC_H264_AVBR
#endif

#ifdef FH_CH0_USING_SAMPLE_H265_AVBR_G3
#define CH0_RC_TYPE_G3 FH_RC_H265_AVBR
#endif

#ifdef FH_CH0_USING_SAMPLE_H264_QVBR_G3
#define CH0_RC_TYPE_G3 FH_RC_H264_QVBR
#endif

#ifdef FH_CH0_USING_SAMPLE_H265_QVBR_G3
#define CH0_RC_TYPE_G3 FH_RC_H265_QVBR
#endif

#ifndef CH0_RC_TYPE_G3
#define CH0_RC_TYPE_G3 0xFF
#endif

/*  CHANNEL 1 */
#ifdef FH_CH1_OPEN_BREATH_EFFECT_G3
#define CH1_BREATH_OPEN_G3 1
#else
#define CH1_BREATH_OPEN_G3 0
#endif

#ifdef FH_CH1_USING_SAMPLE_H264_FIXQP_G3
#define CH1_RC_TYPE_G3 FH_RC_H264_FIXQP
#endif

#ifdef FH_CH1_USING_SAMPLE_H265_FIXQP_G3
#define CH1_RC_TYPE_G3 FH_RC_H265_FIXQP
#endif

#ifdef FH_CH1_USING_SAMPLE_MJPEG_FIXQP_G3
#define CH1_MJPEG_RC_TYPE_G3 FH_RC_MJPEG_FIXQP
#endif

#ifdef FH_CH1_USING_SAMPLE_H264_VBR_G3
#define CH1_RC_TYPE_G3 FH_RC_H264_VBR
#endif

#ifdef FH_CH1_USING_SAMPLE_H265_VBR_G3
#define CH1_RC_TYPE_G3 FH_RC_H265_VBR
#endif

#ifdef FH_CH1_USING_SAMPLE_MJPEG_CBR_G3
#define CH1_MJPEG_RC_TYPE_G3 FH_RC_MJPEG_CBR
#endif

#ifdef FH_CH1_USING_SAMPLE_MJPEG_VBR_G3
#define CH1_MJPEG_RC_TYPE_G3 FH_RC_MJPEG_VBR
#endif

#ifdef FH_CH1_USING_SAMPLE_H264_CBR_G3
#define CH1_RC_TYPE_G3 FH_RC_H264_CBR
#endif

#ifdef FH_CH1_USING_SAMPLE_H265_CBR_G3
#define CH1_RC_TYPE_G3 FH_RC_H265_CBR
#endif

#ifdef FH_CH1_USING_SAMPLE_H264_CVBR_G3
#define CH1_RC_TYPE_G3 FH_RC_H264_CVBR
#endif

#ifdef FH_CH1_USING_SAMPLE_H265_CVBR_G3
#define CH1_RC_TYPE_G3 FH_RC_H265_CVBR
#endif

#ifdef FH_CH1_USING_SAMPLE_H264_AVBR_G3
#define CH1_RC_TYPE_G3 FH_RC_H264_AVBR
#endif

#ifdef FH_CH1_USING_SAMPLE_H265_AVBR_G3
#define CH1_RC_TYPE_G3 FH_RC_H265_AVBR
#endif

#ifdef FH_CH1_USING_SAMPLE_H264_QVBR_G3
#define CH1_RC_TYPE_G3 FH_RC_H264_QVBR
#endif

#ifdef FH_CH1_USING_SAMPLE_H265_QVBR_G3
#define CH1_RC_TYPE_G3 FH_RC_H265_QVBR
#endif

#ifndef CH1_RC_TYPE_G3
#define CH1_RC_TYPE_G3 0xFF
#endif

/* CHANNLE 2 */
#ifdef FH_CH2_OPEN_BREATH_EFFECT_G3
#define CH2_BREATH_OPEN_G3 1
#else
#define CH2_BREATH_OPEN_G3 0
#endif

#ifdef FH_CH2_USING_SAMPLE_H264_FIXQP_G3
#define CH2_RC_TYPE_G3 FH_RC_H264_FIXQP
#endif

#ifdef FH_CH2_USING_SAMPLE_H265_FIXQP_G3
#define CH2_RC_TYPE_G3 FH_RC_H265_FIXQP
#endif

#ifdef FH_CH2_USING_SAMPLE_MJPEG_FIXQP_G3
#define CH2_MJPEG_RC_TYPE_G3 FH_RC_MJPEG_FIXQP
#endif

#ifdef FH_CH2_USING_SAMPLE_H264_VBR_G3
#define CH2_RC_TYPE_G3 FH_RC_H264_VBR
#endif

#ifdef FH_CH2_USING_SAMPLE_H265_VBR_G3
#define CH2_RC_TYPE_G3 FH_RC_H265_VBR
#endif

#ifdef FH_CH2_USING_SAMPLE_MJPEG_CBR_G3
#define CH2_MJPEG_RC_TYPE_G3 FH_RC_MJPEG_CBR
#endif

#ifdef FH_CH2_USING_SAMPLE_MJPEG_VBR_G3
#define CH2_MJPEG_RC_TYPE_G3 FH_RC_MJPEG_VBR
#endif

#ifdef FH_CH2_USING_SAMPLE_H264_CBR_G3
#define CH2_RC_TYPE_G3 FH_RC_H264_CBR
#endif

#ifdef FH_CH2_USING_SAMPLE_H265_CBR_G3
#define CH2_RC_TYPE_G3 FH_RC_H265_CBR
#endif

#ifdef FH_CH2_USING_SAMPLE_H264_CVBR_G3
#define CH2_RC_TYPE_G3 FH_RC_H264_CVBR
#endif

#ifdef FH_CH2_USING_SAMPLE_H265_CVBR_G3
#define CH2_RC_TYPE_G3 FH_RC_H265_CVBR
#endif

#ifdef FH_CH2_USING_SAMPLE_H264_AVBR_G3
#define CH2_RC_TYPE_G3 FH_RC_H264_AVBR
#endif

#ifdef FH_CH2_USING_SAMPLE_H265_AVBR_G3
#define CH2_RC_TYPE_G3 FH_RC_H265_AVBR
#endif

#ifdef FH_CH2_USING_SAMPLE_H264_QVBR_G3
#define CH2_RC_TYPE_G3 FH_RC_H264_QVBR
#endif

#ifdef FH_CH2_USING_SAMPLE_H265_QVBR_G3
#define CH2_RC_TYPE_G3 FH_RC_H265_QVBR
#endif

#ifndef CH2_RC_TYPE_G3
#define CH2_RC_TYPE_G3 0xFF
#endif

/* CHANNEL 3 */
#ifdef FH_CH3_OPEN_BREATH_EFFECT_G3
#define CH3_BREATH_OPEN_G3 1
#else
#define CH3_BREATH_OPEN_G3 0
#endif

#ifdef FH_CH3_USING_SAMPLE_H264_FIXQP_G3
#define CH3_RC_TYPE_G3 FH_RC_H264_FIXQP
#endif

#ifdef FH_CH3_USING_SAMPLE_H265_FIXQP_G3
#define CH3_RC_TYPE_G3 FH_RC_H265_FIXQP
#endif

#ifdef FH_CH3_USING_SAMPLE_MJPEG_FIXQP_G3
#define CH3_MJPEG_RC_TYPE_G3 FH_RC_MJPEG_FIXQP
#endif

#ifdef FH_CH3_USING_SAMPLE_H264_VBR_G3
#define CH3_RC_TYPE_G3 FH_RC_H264_VBR
#endif

#ifdef FH_CH3_USING_SAMPLE_H265_VBR_G3
#define CH3_RC_TYPE_G3 FH_RC_H265_VBR
#endif

#ifdef FH_CH3_USING_SAMPLE_MJPEG_CBR_G3
#define CH3_MJPEG_RC_TYPE_G3 FH_RC_MJPEG_CBR
#endif

#ifdef FH_CH3_USING_SAMPLE_MJPEG_VBR_G3
#define CH3_MJPEG_RC_TYPE_G3 FH_RC_MJPEG_VBR
#endif

#ifdef FH_CH3_USING_SAMPLE_H264_CBR_G3
#define CH3_RC_TYPE_G3 FH_RC_H264_CBR
#endif

#ifdef FH_CH3_USING_SAMPLE_H265_CBR_G3
#define CH3_RC_TYPE_G3 FH_RC_H265_CBR
#endif

#ifdef FH_CH3_USING_SAMPLE_H264_CVBR_G3
#define CH3_RC_TYPE_G3 FH_RC_H264_CVBR
#endif

#ifdef FH_CH3_USING_SAMPLE_H265_CVBR_G3
#define CH3_RC_TYPE_G3 FH_RC_H265_CVBR
#endif

#ifdef FH_CH3_USING_SAMPLE_H264_AVBR_G3
#define CH3_RC_TYPE_G3 FH_RC_H264_AVBR
#endif

#ifdef FH_CH3_USING_SAMPLE_H265_AVBR_G3
#define CH3_RC_TYPE_G3 FH_RC_H265_AVBR
#endif

#ifdef FH_CH3_USING_SAMPLE_H264_QVBR_G3
#define CH3_RC_TYPE_G3 FH_RC_H264_QVBR
#endif

#ifdef FH_CH3_USING_SAMPLE_H265_QVBR_G3
#define CH3_RC_TYPE_G3 FH_RC_H265_QVBR
#endif

#ifndef CH3_RC_TYPE_G3
#define CH3_RC_TYPE_G3 0xFF
#endif

/* CHANNEL 4 */
#ifdef FH_CH4_OPEN_BREATH_EFFECT_G3
#define CH4_BREATH_OPEN_G3 1
#else
#define CH4_BREATH_OPEN_G3 0
#endif

#ifdef FH_CH4_USING_SAMPLE_H264_FIXQP_G3
#define CH4_RC_TYPE_G3 FH_RC_H264_FIXQP
#endif

#ifdef FH_CH4_USING_SAMPLE_H265_FIXQP_G3
#define CH4_RC_TYPE_G3 FH_RC_H265_FIXQP
#endif

#ifdef FH_CH4_USING_SAMPLE_MJPEG_FIXQP_G3
#define CH4_MJPEG_RC_TYPE_G3 FH_RC_MJPEG_FIXQP
#endif

#ifdef FH_CH4_USING_SAMPLE_H264_VBR_G3
#define CH4_RC_TYPE_G3 FH_RC_H264_VBR
#endif

#ifdef FH_CH4_USING_SAMPLE_H265_VBR_G3
#define CH4_RC_TYPE_G3 FH_RC_H265_VBR
#endif

#ifdef FH_CH4_USING_SAMPLE_MJPEG_CBR_G3
#define CH4_MJPEG_RC_TYPE_G3 FH_RC_MJPEG_CBR
#endif

#ifdef FH_CH4_USING_SAMPLE_MJPEG_VBR_G3
#define CH4_MJPEG_RC_TYPE_G3 FH_RC_MJPEG_VBR
#endif

#ifdef FH_CH4_USING_SAMPLE_H264_CBR_G3
#define CH4_RC_TYPE_G3 FH_RC_H264_CBR
#endif

#ifdef FH_CH4_USING_SAMPLE_H265_CBR_G3
#define CH4_RC_TYPE_G3 FH_RC_H265_CBR
#endif

#ifdef FH_CH4_USING_SAMPLE_H264_CVBR_G3
#define CH4_RC_TYPE_G3 FH_RC_H264_CVBR
#endif

#ifdef FH_CH4_USING_SAMPLE_H265_CVBR_G3
#define CH4_RC_TYPE_G3 FH_RC_H265_CVBR
#endif

#ifdef FH_CH4_USING_SAMPLE_H264_AVBR_G3
#define CH4_RC_TYPE_G3 FH_RC_H264_AVBR
#endif

#ifdef FH_CH4_USING_SAMPLE_H265_AVBR_G3
#define CH4_RC_TYPE_G3 FH_RC_H265_AVBR
#endif

#ifdef FH_CH4_USING_SAMPLE_H264_QVBR_G3
#define CH4_RC_TYPE_G3 FH_RC_H264_QVBR
#endif

#ifdef FH_CH4_USING_SAMPLE_H265_QVBR_G3
#define CH4_RC_TYPE_G3 FH_RC_H265_QVBR
#endif

#ifndef CH4_RC_TYPE_G3
#define CH4_RC_TYPE_G3 0xFF
#endif

#endif /* VIDEO_GRP3 */

#ifdef VIDEO_GRP0

#ifdef FH_CH0_USING_SAMPLE_H264_G0
#define CH0_ENC_TYPE_G0 FH_NORMAL_H264
#endif

#ifdef FH_CH0_USING_SAMPLE_S264_G0
#define CH0_ENC_TYPE_G0 FH_SMART_H264
#endif

#ifdef FH_CH0_USING_SAMPLE_H265_G0
#define CH0_ENC_TYPE_G0 FH_NORMAL_H265
#endif

#ifdef FH_CH0_USING_SAMPLE_S265_G0
#define CH0_ENC_TYPE_G0 FH_SMART_H265
#endif

#ifdef FH_CH0_USING_SAMPLE_MJPEG_G0
#define CH0_ENC_TYPE_G0 FH_MJPEG
#endif

#ifdef FH_CH0_USING_SAMPLE_JPEG_G0
#define CH0_ENC_TYPE_G0 FH_JPEG
#endif

#ifdef FH_CH1_USING_SAMPLE_H264_G0
#define CH1_ENC_TYPE_G0 FH_NORMAL_H264
#endif

#ifdef FH_CH1_USING_SAMPLE_S264_G0
#define CH1_ENC_TYPE_G0 FH_SMART_H264
#endif

#ifdef FH_CH1_USING_SAMPLE_H265_G0
#define CH1_ENC_TYPE_G0 FH_NORMAL_H265
#endif

#ifdef FH_CH1_USING_SAMPLE_S265_G0
#define CH1_ENC_TYPE_G0 FH_SMART_H265
#endif

#ifdef FH_CH1_USING_SAMPLE_MJPEG_G0
#define CH1_ENC_TYPE_G0 FH_MJPEG
#endif

#ifndef CH1_ENC_TYPE_G0
#define CH1_ENC_TYPE_G0 0
#endif

#ifdef FH_CH2_USING_SAMPLE_H264_G0
#define CH2_ENC_TYPE_G0 FH_NORMAL_H264
#endif

#ifdef FH_CH2_USING_SAMPLE_S264_G0
#define CH2_ENC_TYPE_G0 FH_SMART_H264
#endif

#ifdef FH_CH2_USING_SAMPLE_H265_G0
#define CH2_ENC_TYPE_G0 FH_NORMAL_H265
#endif

#ifdef FH_CH2_USING_SAMPLE_S265_G0
#define CH2_ENC_TYPE_G0 FH_SMART_H265
#endif

#ifdef FH_CH2_USING_SAMPLE_MJPEG_G0
#define CH2_ENC_TYPE_G0 FH_MJPEG
#endif

#ifndef CH2_ENC_TYPE_G0
#define CH2_ENC_TYPE_G0 0
#endif

#ifdef FH_CH3_USING_SAMPLE_H264_G0
#define CH3_ENC_TYPE_G0 FH_NORMAL_H264
#endif

#ifdef FH_CH3_USING_SAMPLE_S264_G0
#define CH3_ENC_TYPE_G0 FH_SMART_H264
#endif

#ifdef FH_CH3_USING_SAMPLE_H265_G0
#define CH3_ENC_TYPE_G0 FH_NORMAL_H265
#endif

#ifdef FH_CH3_USING_SAMPLE_S265_G0
#define CH3_ENC_TYPE_G0 FH_SMART_H265
#endif

#ifdef FH_CH3_USING_SAMPLE_MJPEG_G0
#define CH3_ENC_TYPE_G0 FH_MJPEG
#endif

#ifndef CH3_ENC_TYPE_G0
#define CH3_ENC_TYPE_G0 0
#endif

#ifdef FH_CH4_USING_SAMPLE_H264_G0
#define CH4_ENC_TYPE_G0 FH_NORMAL_H264
#endif

#ifdef FH_CH4_USING_SAMPLE_S264_G0
#define CH4_ENC_TYPE_G0 FH_SMART_H264
#endif

#ifdef FH_CH4_USING_SAMPLE_H265_G0
#define CH4_ENC_TYPE_G0 FH_NORMAL_H265
#endif

#ifdef FH_CH4_USING_SAMPLE_S265_G0
#define CH4_ENC_TYPE_G0 FH_SMART_H265
#endif

#ifdef FH_CH4_USING_SAMPLE_MJPEG_G0
#define CH4_ENC_TYPE_G0 FH_MJPEG
#endif

#ifndef CH4_ENC_TYPE_G0
#define CH4_ENC_TYPE_G0 0
#endif

#endif /* VIDEO_GRP0 */
#ifdef VIDEO_GRP1

#ifdef FH_CH0_USING_SAMPLE_H264_G1
#define CH0_ENC_TYPE_G1 FH_NORMAL_H264
#endif

#ifdef FH_CH0_USING_SAMPLE_S264_G1
#define CH0_ENC_TYPE_G1 FH_SMART_H264
#endif

#ifdef FH_CH0_USING_SAMPLE_H265_G1
#define CH0_ENC_TYPE_G1 FH_NORMAL_H265
#endif

#ifdef FH_CH0_USING_SAMPLE_S265_G1
#define CH0_ENC_TYPE_G1 FH_SMART_H265
#endif

#ifdef FH_CH0_USING_SAMPLE_MJPEG_G1
#define CH0_ENC_TYPE_G1 FH_MJPEG
#endif

#ifdef FH_CH1_USING_SAMPLE_H264_G1
#define CH1_ENC_TYPE_G1 FH_NORMAL_H264
#endif

#ifdef FH_CH1_USING_SAMPLE_S264_G1
#define CH1_ENC_TYPE_G1 FH_SMART_H264
#endif

#ifdef FH_CH1_USING_SAMPLE_H265_G1
#define CH1_ENC_TYPE_G1 FH_NORMAL_H265
#endif

#ifdef FH_CH1_USING_SAMPLE_S265_G1
#define CH1_ENC_TYPE_G1 FH_SMART_H265
#endif

#ifdef FH_CH1_USING_SAMPLE_MJPEG_G1
#define CH1_ENC_TYPE_G1 FH_MJPEG
#endif

#ifndef CH1_ENC_TYPE_G1
#define CH1_ENC_TYPE_G1 0
#endif

#ifdef FH_CH2_USING_SAMPLE_H264_G1
#define CH2_ENC_TYPE_G1 FH_NORMAL_H264
#endif

#ifdef FH_CH2_USING_SAMPLE_S264_G1
#define CH2_ENC_TYPE_G1 FH_SMART_H264
#endif

#ifdef FH_CH2_USING_SAMPLE_H265_G1
#define CH2_ENC_TYPE_G1 FH_NORMAL_H265
#endif

#ifdef FH_CH2_USING_SAMPLE_S265_G1
#define CH2_ENC_TYPE_G1 FH_SMART_H265
#endif

#ifdef FH_CH2_USING_SAMPLE_MJPEG_G1
#define CH2_ENC_TYPE_G1 FH_MJPEG
#endif

#ifndef CH2_ENC_TYPE_G1
#define CH2_ENC_TYPE_G1 0
#endif

#ifdef FH_CH3_USING_SAMPLE_H264_G1
#define CH3_ENC_TYPE_G1 FH_NORMAL_H264
#endif

#ifdef FH_CH3_USING_SAMPLE_S264_G1
#define CH3_ENC_TYPE_G1 FH_SMART_H264
#endif

#ifdef FH_CH3_USING_SAMPLE_H265_G1
#define CH3_ENC_TYPE_G1 FH_NORMAL_H265
#endif

#ifdef FH_CH3_USING_SAMPLE_S265_G1
#define CH3_ENC_TYPE_G1 FH_SMART_H265
#endif

#ifdef FH_CH3_USING_SAMPLE_MJPEG_G1
#define CH3_ENC_TYPE_G1 FH_MJPEG
#endif

#ifndef CH3_ENC_TYPE_G1
#define CH3_ENC_TYPE_G1 0
#endif

#ifdef FH_CH4_USING_SAMPLE_H264_G1
#define CH4_ENC_TYPE_G1 FH_NORMAL_H264
#endif

#ifdef FH_CH4_USING_SAMPLE_S264_G1
#define CH4_ENC_TYPE_G1 FH_SMART_H264
#endif

#ifdef FH_CH4_USING_SAMPLE_H265_G1
#define CH4_ENC_TYPE_G1 FH_NORMAL_H265
#endif

#ifdef FH_CH4_USING_SAMPLE_S265_G1
#define CH4_ENC_TYPE_G1 FH_SMART_H265
#endif

#ifdef FH_CH4_USING_SAMPLE_MJPEG_G1
#define CH4_ENC_TYPE_G1 FH_MJPEG
#endif

#ifndef CH4_ENC_TYPE_G1
#define CH4_ENC_TYPE_G1 0
#endif

#endif /* VIDEO_GRP1 */
#ifdef VIDEO_GRP2

#ifdef FH_CH0_USING_SAMPLE_H264_G2
#define CH0_ENC_TYPE_G2 FH_NORMAL_H264
#endif

#ifdef FH_CH0_USING_SAMPLE_S264_G2
#define CH0_ENC_TYPE_G2 FH_SMART_H264
#endif

#ifdef FH_CH0_USING_SAMPLE_H265_G2
#define CH0_ENC_TYPE_G2 FH_NORMAL_H265
#endif

#ifdef FH_CH0_USING_SAMPLE_S265_G2
#define CH0_ENC_TYPE_G2 FH_SMART_H265
#endif

#ifdef FH_CH0_USING_SAMPLE_MJPEG_G2
#define CH0_ENC_TYPE_G2 FH_MJPEG
#endif

#ifdef FH_CH1_USING_SAMPLE_H264_G2
#define CH1_ENC_TYPE_G2 FH_NORMAL_H264
#endif

#ifdef FH_CH1_USING_SAMPLE_S264_G2
#define CH1_ENC_TYPE_G2 FH_SMART_H264
#endif

#ifdef FH_CH1_USING_SAMPLE_H265_G2
#define CH1_ENC_TYPE_G2 FH_NORMAL_H265
#endif

#ifdef FH_CH1_USING_SAMPLE_S265_G2
#define CH1_ENC_TYPE_G2 FH_SMART_H265
#endif

#ifdef FH_CH1_USING_SAMPLE_MJPEG_G2
#define CH1_ENC_TYPE_G2 FH_MJPEG
#endif

#ifndef CH1_ENC_TYPE_G2
#define CH1_ENC_TYPE_G2 0
#endif

#ifdef FH_CH2_USING_SAMPLE_H264_G2
#define CH2_ENC_TYPE_G2 FH_NORMAL_H264
#endif

#ifdef FH_CH2_USING_SAMPLE_S264_G2
#define CH2_ENC_TYPE_G2 FH_SMART_H264
#endif

#ifdef FH_CH2_USING_SAMPLE_H265_G2
#define CH2_ENC_TYPE_G2 FH_NORMAL_H265
#endif

#ifdef FH_CH2_USING_SAMPLE_S265_G2
#define CH2_ENC_TYPE_G2 FH_SMART_H265
#endif

#ifdef FH_CH2_USING_SAMPLE_MJPEG_G2
#define CH2_ENC_TYPE_G2 FH_MJPEG
#endif

#ifndef CH2_ENC_TYPE_G2
#define CH2_ENC_TYPE_G2 0
#endif

#ifdef FH_CH3_USING_SAMPLE_H264_G2
#define CH3_ENC_TYPE_G2 FH_NORMAL_H264
#endif

#ifdef FH_CH3_USING_SAMPLE_S264_G2
#define CH3_ENC_TYPE_G2 FH_SMART_H264
#endif

#ifdef FH_CH3_USING_SAMPLE_H265_G2
#define CH3_ENC_TYPE_G2 FH_NORMAL_H265
#endif

#ifdef FH_CH3_USING_SAMPLE_S265_G2
#define CH3_ENC_TYPE_G2 FH_SMART_H265
#endif

#ifdef FH_CH3_USING_SAMPLE_MJPEG_G2
#define CH3_ENC_TYPE_G2 FH_MJPEG
#endif

#ifndef CH3_ENC_TYPE_G2
#define CH3_ENC_TYPE_G2 0
#endif

#ifdef FH_CH4_USING_SAMPLE_H264_G2
#define CH4_ENC_TYPE_G2 FH_NORMAL_H264
#endif

#ifdef FH_CH4_USING_SAMPLE_S264_G2
#define CH4_ENC_TYPE_G2 FH_SMART_H264
#endif

#ifdef FH_CH4_USING_SAMPLE_H265_G2
#define CH4_ENC_TYPE_G2 FH_NORMAL_H265
#endif

#ifdef FH_CH4_USING_SAMPLE_S265_G2
#define CH4_ENC_TYPE_G2 FH_SMART_H265
#endif

#ifdef FH_CH4_USING_SAMPLE_MJPEG_G2
#define CH4_ENC_TYPE_G2 FH_MJPEG
#endif

#ifndef CH4_ENC_TYPE_G2
#define CH4_ENC_TYPE_G2 0
#endif

#endif /* VIDEO_GRP2 */
#ifdef VDEC_SEND_G3

#ifdef FH_CH0_USING_SAMPLE_H264_G3
#define CH0_ENC_TYPE_G3 FH_NORMAL_H264
#endif

#ifdef FH_CH0_USING_SAMPLE_S264_G3
#define CH0_ENC_TYPE_G3 FH_SMART_H264
#endif

#ifdef FH_CH0_USING_SAMPLE_H265_G3
#define CH0_ENC_TYPE_G3 FH_NORMAL_H265
#endif

#ifdef FH_CH0_USING_SAMPLE_S265_G3
#define CH0_ENC_TYPE_G3 FH_SMART_H265
#endif

#ifdef FH_CH0_USING_SAMPLE_MJPEG_G3
#define CH0_ENC_TYPE_G3 FH_MJPEG
#endif

#ifdef FH_CH1_USING_SAMPLE_H264_G3
#define CH1_ENC_TYPE_G3 FH_NORMAL_H264
#endif

#ifdef FH_CH1_USING_SAMPLE_S264_G3
#define CH1_ENC_TYPE_G3 FH_SMART_H264
#endif

#ifdef FH_CH1_USING_SAMPLE_H265_G3
#define CH1_ENC_TYPE_G3 FH_NORMAL_H265
#endif

#ifdef FH_CH1_USING_SAMPLE_S265_G3
#define CH1_ENC_TYPE_G3 FH_SMART_H265
#endif

#ifdef FH_CH1_USING_SAMPLE_MJPEG_G3
#define CH1_ENC_TYPE_G3 FH_MJPEG
#endif

#ifndef CH1_ENC_TYPE_G3
#define CH1_ENC_TYPE_G3 0
#endif

#ifdef FH_CH2_USING_SAMPLE_H264_G3
#define CH2_ENC_TYPE_G3 FH_NORMAL_H264
#endif

#ifdef FH_CH2_USING_SAMPLE_S264_G3
#define CH2_ENC_TYPE_G3 FH_SMART_H264
#endif

#ifdef FH_CH2_USING_SAMPLE_H265_G3
#define CH2_ENC_TYPE_G3 FH_NORMAL_H265
#endif

#ifdef FH_CH2_USING_SAMPLE_S265_G3
#define CH2_ENC_TYPE_G3 FH_SMART_H265
#endif

#ifdef FH_CH2_USING_SAMPLE_MJPEG_G3
#define CH2_ENC_TYPE_G3 FH_MJPEG
#endif

#ifndef CH2_ENC_TYPE_G3
#define CH2_ENC_TYPE_G3 0
#endif

#ifdef FH_CH3_USING_SAMPLE_H264_G3
#define CH3_ENC_TYPE_G3 FH_NORMAL_H264
#endif

#ifdef FH_CH3_USING_SAMPLE_S264_G3
#define CH3_ENC_TYPE_G3 FH_SMART_H264
#endif

#ifdef FH_CH3_USING_SAMPLE_H265_G3
#define CH3_ENC_TYPE_G3 FH_NORMAL_H265
#endif

#ifdef FH_CH3_USING_SAMPLE_S265_G3
#define CH3_ENC_TYPE_G3 FH_SMART_H265
#endif

#ifdef FH_CH3_USING_SAMPLE_MJPEG_G3
#define CH3_ENC_TYPE_G3 FH_MJPEG
#endif

#ifndef CH3_ENC_TYPE_G3
#define CH3_ENC_TYPE_G3 0
#endif

#ifdef FH_CH4_USING_SAMPLE_H264_G3
#define CH4_ENC_TYPE_G3 FH_NORMAL_H264
#endif

#ifdef FH_CH4_USING_SAMPLE_S264_G3
#define CH4_ENC_TYPE_G3 FH_SMART_H264
#endif

#ifdef FH_CH4_USING_SAMPLE_H265_G3
#define CH4_ENC_TYPE_G3 FH_NORMAL_H265
#endif

#ifdef FH_CH4_USING_SAMPLE_S265_G3
#define CH4_ENC_TYPE_G3 FH_SMART_H265
#endif

#ifdef FH_CH4_USING_SAMPLE_MJPEG_G3
#define CH4_ENC_TYPE_G3 FH_MJPEG
#endif

#ifndef CH4_ENC_TYPE_G3
#define CH4_ENC_TYPE_G3 0
#endif

#endif /* VIDEO_GRP3 */

#define H264_COMMON_BUFFER_SIZE 1024 * 1024 * 2 // 2MByte
#define H265_COMMON_BUFFER_SIZE 1024 * 1024 * 2 // 2MByte
#define JPEG_COMMON_BUFFER_SIZE 1024 * 1024 * 1 // 1MByte
#define MJPEG_COMMON_BUFFER_SIZE 1024 * 1024 * 2  // 2MByte

#endif /* __FBV__ENC_CONFIG_H__ */
