#ifndef BASE_APP_COMMAND_DEFS_H_
#define BASE_APP_COMMAND_DEFS_H_

#define APP_CMD_CALL_LOCALE_FUNCTION (0x03)
#define APP_CMD_SYNC_TIME (0x04)
#define APP_CMD_QUERY_BATTERY_LEVEL (0x05)
#define APP_CMD_CONFIG_WIFI (0x06)
#define APP_CMD_QUERY_FILE_LIST (0x07)
#define APP_CMD_FORMAT_SD_CARD (0x08)
#define APP_CMD_OAT_STARTUP (0x09)
#define APP_CMD_RUN_AS_AP (0x10)
#define APP_CMD_HELLO (0x11)
#define APP_CMD_POWEROFF (0x12)
#define APP_CMD_TAKE_PHOTO (0x13)
#define APP_CMD_VERSION (0x15)

#define APP_CMD_CONFIRM_WIFICONFIG (0x17)
#define APP_CMD_OTA_PROGRESS (0x18)
#define APP_CMD_RECORDING (0x19)
#define APP_CMD_PHOTOING (0x20)
#define APP_CMD_SET_RECORD_MAXTIME (0x25)
#define APP_CMD_LAUNCH_P2P (0x29)

#define APP_CMD_WIFI_IS_CONNECTED (0x32)
#define APP_CMD_REQUEST_FILE_LIST (0x33)
#define APP_CMD_SET_P2P_NAME (0x34)



#define PRESS_BUTTON_START_RECORD (0x50)
#define PRESS_BUTTON_STOP_RECORD (0x51)
#define APP_CMD_REBOOT (0xFF)


#define APP_CMD_LPC_TAKE_PHOTO_TO_FILE (0x01)
#define APP_CMD_LPC_TAKE_PHOTO_IN_MEMORY (0x02)
#define APP_CMD_LPC_START_RECORD (0x03)
#define APP_CMD_LPC_STOP_RECORD (0x04)

#define DEV_ID_APP (0x02)
#define DEV_ID_MASTER (0x03)

// octonary number
#define GPIO3_6 (036)

#endif  // BASE_APP_COMMAND_DEFS_H_
